### ISSUE TITLE
Fill out docs in docs directory

### ISSUE THREAD

**Issue by robconery** [dmfay/massive-js#109]
I've setup a readthedocs.org site that's pulling from our repo here... looks pretty good:
http://massive-js.readthedocs.org/en/latest/

I just need to fill it out. I started a skeleton that can be added/tweaked but if you guys had some time to help me here and there I'd really appreciate!

**Comment by xivSolutions** [comment]
Love it...I'll make some time this week. Been getting up to speed on the new job, so time has been tight.

**Comment by dmfay** [comment]
We've got a deadline coming up next month so I don't know how much I'll be able to contribute until that's over but I'll see what I can do!

**Comment by seymores** [comment]
I would love to help out with the docs but I am not sure how to fork the docs, or is the docs at readthedocs abandoned?

**Comment by xivSolutions** [comment]
Just fork the project - the docs all live in the `docs` [directory](https://github.com/robconery/massive-js/tree/master/docs)

**Comment by robinjmurphy** [comment]
Was there a plan for the API docs in `docs/API/tables.md` and `docs/API/functions.md`? I'm guessing some kind of full API docs.

I've got a branch where I've started to fill out the docs for the table's `.find` method. Would be interested to see if you like the approach/style.

An alternative to doing this manually would be to use JSDoc and generate the Markdown from that. Happy to get writing these once there's an agreed approach.

https://github.com/robinjmurphy/massive-js/blob/api-docs/docs/API/tables.md

<img width="1098" alt="screen shot 2016-01-29 at 13 34 05" src="https://cloud.githubusercontent.com/assets/917111/12676858/01ad2816-c68d-11e5-813c-bbbe7e20c160.png">

**Comment by xivSolutions** [comment]
I like it! :-) I think API docs like the above are especially helpful with JS. 

I think a more notes about the (possible) return type for a given function is in order here. For example, the `find` method, and many others, will return either an array of row objects, or a single object, depending. This is handy, but can be confusing if it's not clear. 

On the one hand I like the idea of generated markdown, as it is easy to maintain. On the other I don't, as it clutters up the code files. 

I say proceed, and shoot a PR. If it were me, I would probably skip the JSDoc, as to do it right REALLY clutters/dirties up the code. @robconery may feel differently.

**Comment by robconery** [comment]
At this point I'll take*whatever* and I'm just extremely grateful you're doing it :). Carry on good sir!

**Comment by robinjmurphy** [comment]
@xivSolutions Agree about the return values being clearer. Maybe a separate section outside of the table. I'll take a look and see what I can come up with.

**Comment by xivSolutions** [comment]
@robinjmurphy - I was thinking in the section where you describe the function, right under the syntax example. Instead of "Returns rows that match the given constraints" maybe just expan on that, with a super-simple example of usage and outputs (or maybe a link to the narrative part of the docs where examples live). 

Once you get things rolling format-wise, I  can try to help some too. I've been swamped recently, but been meaning to get back to some of this myself.

**Comment by robinjmurphy** [comment]
I've made an update to the format. I've included an example at the top of each function. I've started to add headings for each method as well. Let me know what you think. If you're happy I'll move the branch out of my fork and into the main repo and we can contribute there.

https://github.com/robconery/massive-js/compare/master...robinjmurphy:api-docs

![docs](https://cloud.githubusercontent.com/assets/917111/12875159/f53db22a-cddb-11e5-918d-0189923b67e0.png)

**Comment by robconery** [comment]
Yes!

**Comment by robinjmurphy** [comment]
Cool. Branch is here if anyone wants to contribute.

https://github.com/robconery/massive-js/tree/api-docs

**Comment by dmfay** [comment]
Moving to github pages for v3, and aside from a couple points which are still in flux the documentation is basically complete on the `promises` branch.
