### ISSUE TITLE
Ability to watch tables in real-time

### ISSUE THREAD

**Issue by jmealo** [dmfay/massive-js#176]
Is there any interest in allowing users to subscribe to insert, update and delete events on a given table without triggers or notify/listen?

I'm the creator of [Lapidus](https://github.com/jarvusinnovations/lapidus) and have been using it in production since the summer with excellent performance and reliability.

I'll be happy to do a pull request adding this functionality, however, it makes use of logical decoding and streaming replication which require additional configuration:
1. Lapidus requires `pg_recvlogical` to be present on the system, it uses `pg_config` to find the correct location of the binary if it cannot be found on the path
2. Logical replication must be configured
3. A logical decoding plugin must be installed (decoding_json)
4. When Massive connects and does it's introspection, it's advisable that it checks for logical replication slots that it created that are inactive and delete them or throw an error or warning when they reach a certain size, **it's possible to run out of disk space**
5. A user with replication permission and the relevant bits in `pg_hba.conf`

I think this amount of configuration/complexity is a bit of a turn off for some massive users, and other than making use of introspection to allow filtering of events by primary keys, Lapidus has no dependencies on having a connection to the database (`pg_recv_logical` does that part).

I think that it'd be easy enough for introspection to make sure that the server is configured properly and that the provided credentials have replication permissions and provide exact instructions on what files to edit, lines to add or changes to make in order for `watch` to be enabled. It could be a skeleton function that throws a helpful error if you try to use it when it's not configured.

**Comment by dmfay** [comment]
Well, I'm not Rob, but looking at it I have to ask: what about this technology is so _generally_ compelling that makes it suitable for bundling into a data access toolkit with a distinctly minimalist, "here's your database and what's in it, everything else is on you, go nuts", mindset? Granted, triggers and pub/sub aren't always sufficient for peoples' needs (or you wouldn't have written this), but: we don't do anything with triggers or pub/sub in the first place. Massive reads and writes data; monitoring is a separate concern.

**Comment by jmealo** [comment]
I think it's a good fit because this is the minimalist way of streaming changes that requires no changes to your database, only its configuration. (No triggers, listen/notify, schema changes are needed).

I could see it going both ways.

Since Lapidus and Massive can play nice together maybe there's no point, however, I think that the same people who would appreciate one would appreciate the simplicity of the other.

I would rather not implement a subset of Massive's features in Lapidus if possible (mostly all of the introspection), I'm trying to avoid keeping a "control connection" open to PostgreSQL if I don't need it.

**Comment by xivSolutions** [comment]
I'm of the mind that pub/sub is a different concern. While it may be handy, it seems like an application concern to me (and I suspect Rob would agree, but you never know...). On the other hand, a complimentary lib, or a pluggable thingy, might be handy...

**Comment by jmealo** [comment]
@xivSolutions Just to clarify, this is not pub sub, this is full streaming of changes at the database level. I just imagined that each table would be an event emitter where you could listen for ``update``, ``insert``, or ``delete`` events.

**Comment by xivSolutions** [comment]
Ahhh...

I thought we had those events in there...

This may have some traction. If they are not there anymore possibly we should add those back in.

**Comment by robconery** [comment]
I was thinking of issuing a `NOTIFY` when a document is saved - I'll have a peak at this in v3.

**Comment by dmfay** [comment]
I thought about this some more and I'm keeping Massive's focus on data mapping; an event system necessitating extra setup is more than I want to get into.
