### ISSUE TITLE
Configure a logger

### ISSUE THREAD

**Issue by aray12** [dmfay/massive-js#218]
It would be awesome if you could pass a logger function in the configuration object. During development I find it useful to `tail -f` a log file for all queries that are supposed to be firing.

**Comment by robconery** [comment]
Some more information would be useful, and I'm always open to PRs :)

**Comment by aray12** [comment]
@robconery What I would expect is being able to pass a function in the configuration object of `massive.connect`. Some like this: 

```javascript
massive.connectSync({
  connectionString: 'postgres://postgres:test@localhost/test-db',
  scripts: path.resolve(__dirname, 'scripts'),
  logger: console.log,
});
```

From there it seems like you could capture all queries in either `DB.prototype.query` and `DB.prototype.stream` in `runner.js`. The main issue is that only argument passed to the `DB` constructor is the connectionString. 

I see 3 potential solutions. 

1. Change the expected parameter in DB to an object that options contains a `logger` property
2. Add an addition parameter called logger
3. Pass the logger as the second parameter and extract it from `arguments` (fairly brittle because code doesn't inherently document order even if it does matter)

I would recommend 1 or 2. I think 1 would allow for better extensibility down the line, but 2 would be quicker to implement and require little refactoring (just additional functionality added)

I don't mind submitting a PR, but, given that I have little experience contributing to OS, I'd prefer to get your feedback on intended implementation/potential obstacles before.

**Comment by robconery** [comment]
Think I'd rather have a dedicated logging package that you can configure. @dmfay do you have any experience with this (logging)? I liked the way ActiveRecord does it for development - we could implement something like that for execution (outputting params, etc with SQL). Thoughts?

**Comment by dmfay** [comment]
Only with Java, I'm afraid. I do think a dedicated module would be appropriate here -- something that offers discrete log levels would allow us to have log statements seamlessly interspersed through the code while only ever capturing messages meeting a level threshold set on startup. Looks like winstonjs/winston supports that at a glance, but I don't know much else about it.

**Comment by aray12** [comment]
In my experience the options for node are [winston](https://github.com/winstonjs/winston) and [bunyan](https://github.com/trentm/node-bunyan). Both are fairly stable packages that support leveled logging like what you want (although both have stagnated in development in my opinion)

In my experience, I prefer a simple function. The reason is I can then tie your logging into which ever logging package I prefer.

**Comment by dmfay** [comment]
There's also [log4js](https://github.com/nomiddlename/log4js-node) which is close to what I'm used to and seems relatively active, but I don't know how mature it is.

Both that and winston at least have the concept of appenders ('transports' in the latter), which we could consume as part of that extra startup configuration. For example if in addition to the log threshold you specified a file appender when initializing Massive, we could use that to write out to the same file you're logging your other stuff to -- assuming there aren't any wacky permissions issues, of course. Otherwise we'd default to logging errors and only errors out to the console, or something along those lines.

**Comment by aray12** [comment]
Bunyan uses the concept of `streams` which are essentially the same where you can set a threshold and pipe to any writable stream (stdout, stderr, file or external service). Either way I think the ability to log generated SQL would be helpful. I am less concerned with logging errors because I catch those with my standard error handling

**Comment by dmfay** [comment]
With pg-promise, Massive is even thinner than it used to be and [pg-monitor](github.com/vitaly-t/pg-monitor) is easy enough to set up.
