### ISSUE TITLE
Get hold of the generated sql without executing the sql-query

### ISSUE THREAD

**Issue by cjnqt** [dmfay/massive-js#221]
I am looking for a way to get hold of the generated sql, without having to execute the query.
Similar to [this](http://knexjs.org/#Other-toString) function.

Why?
- It would allow massive to be used as a query builder
- Useful for debugging (view what queries were generated)
- Makes it possible to create quick transactions:

```
db.query([
    'BEGIN',
    db.users.save({ name: 'Peter' }, {toString:true}),
    db.users.save({ name: 'OtherGuy' }, {toString:true}),
    'COMMIT'
  ].join(';'), function(...)
})
```

What do you think – good idea? 

I tried an implementation (by setting the key 'toString' in the options object, as above) but it didn't work – I had totally missed how options are passed to the query runner. Do you have other ideas for an implementation?

**Comment by xivSolutions** [comment]
Assistance with building SQL is something we talked about adding a ways back. I like the idea. Note, however, that there may be challenges with managing parameters across multiple statements (among other things). It seems like there should be an easy way to do this, but I suspect it may be a little more disruptive than it appears at first.

**Comment by cjnqt** [comment]
Both this issue and #206 could be implemented quite simply if we had a way to pass options to the query runner. As @dmfay mentioned in that issue, _"this is hard since because of how Executable.invoke() sorts out its arguments. You can pass up to three args: parameters (primitive or array), options (object; currently just used to toggle results streaming), and callback. Since both parameters and options are optional, it checks the types of what you pass it and assumes an object is the options and anything else is the parameters._

In v 3.0, I think having a way to pass options to the query runner would make sense.

**Comment by robconery** [comment]
I'm going to put this against 3.0; it's a good idea, as is better logging.
