### ISSUE TITLE
*Sync functions on instances created with async connect() hang

### ISSUE THREAD

**Issue by AdamAndersonFalafelSoftware** [dmfay/massive-js#276]
``` js
massive.connect({ connectionString }, function f(err, db) {
  db.things.find({}, function a(err, things) {
    // this works
    console.log(things)
    // this will hang
    console.log(db.things.findSync({}))
    db.end()
  })
})
```

...not that there is any good reason to do this at all. I stumbled upon it by accident. The opposite scenario works as expected: instances constructed with connectSync() can use both async and sync methods without hanging.

**Comment by robconery** [comment]
I would guess it's hanging on `db.end()` because when you call `findSync` we close the current connection. Thanks for letting me know - not sure what we can do about it. We *will* be booting the sync stuff in the next rev.

**Comment by AdamAndersonFalafelSoftware** [comment]
Yeah, I didn't figure it's exactly a high priority. :) But I can confirm for sure that it hangs on findSync, *not* on end(). For whatever it's worth.

**Comment by robconery** [comment]
Hmmm - OK. It *is* an interesting thing to try and figure out. The hang could be coming from a callback weirdness or from PG itself. If a transaction is open, for instance, and we try to write outside of it with another transaction, we'll get a block.

But these are read only... which tells me that it's a callback notting getting fired. Yuck - the sync stuff is a mess. I'll bet we're trying to reuse a connection (from node-pg) that already has a pending operation.

Do me a favor? Move `db.end()` up a line?

**Comment by AdamAndersonFalafelSoftware** [comment]
Oh, this is too good. Not only does end() work, but the findSync() afterwards does too!

`massive.connect({ connectionString: config.postgres.uri }, function f(err, db) {
  log('connected')
  db.thing.find({}, function a(err, things) {
    log('this works')
    dir(things)
    log('will this?')
    db.end()
    log('closed')
    log('this probably still won\'t')
    dir(db.thing.findSync())
    log('it did???')
  })
})`

(log and dir are just aliases for the console methods)

**Comment by robconery** [comment]
I have a feeling this might be at the driver level - or at least how we're using the driver. The sync thing is so useful, but it's such a bad idea.

**Comment by AdamAndersonFalafelSoftware** [comment]
I _was_ going to say that all you need in order to write sync-looking code is "just" to promisify the async calls, then inside a coroutine use the yield keyword... which I do without really thinking about it, but it sure sounds like a mouthful to say, even in its shortest form!

**Comment by dmfay** [comment]
Sync methods are out in v3.
