### ISSUE TITLE
Multi prepared statements 

### ISSUE THREAD

**Issue by mcornut** [dmfay/massive-js#280]
Hi,

I would like to create a transaction with multiple inserts (prepared statements) but it seems to be impossible, despite the fact @robconery suggests it is super easy in #163.

`Multi-statement parameterized queries are currently not supported by postgres.` (https://github.com/brianc/node-postgres/wiki/Prepared-Statements#parameterized-queries)
The only way I founded was to create a function instead of a db file. 

**DB File** : 

``` sql
BEGIN;
PREPARE myTest(TEXT, TEXT) AS
  INSERT INTO myTable (column1) values ($1), ($2);
END;
```

=> `ERROR:  cannot insert multiple commands into a prepared statement`

**Function** : 

``` sql
BEGIN;
  CREATE OR REPLACE FUNCTION myFunctionTest(
    value1 TEXT,
    value2 TEXT
  )
RETURNS void AS $$

BEGIN;
PREPARE myTest(TEXT, TEXT) AS
  INSERT INTO myTable (column1) values ($1), ($2);
END;

$$ language 'plpgsql';
END;
```

Do you know any tips to do it with a db file ?

Thanks.

**Comment by robconery** [comment]
We already wrap the file in a transaction so you don't need to add your own `BEGIN` and `END`. Also - the driver is not terribly sophisticated and it isn't designed to handle multiple calls to the DB. We can fool it a bit if we structure the query in a simple way (which is what we do on test spin up).

So: just roll in the `INSERTS` inline, separated with a `;` and you should be OK.

**Comment by mcornut** [comment]
Thanks for your answer.
FYI : 

**If I use only 1 insert:**
```sql
INSERT INTO myTable (column1) values ($1), ($2);
```
=>  It works ! 👍 

**If I use 2 inserts:**
```sql
INSERT INTO myTable (column1) values ($1);
INSERT INTO myTable (column1) values ($2);
```
=> 
`postgres_1 | ERROR:  cannot insert multiple commands into a prepared statement`
`postgres_1 | STATEMENT:  INSERT INTO myTable (column1) values ($1);`
`postgres_1 | 	INSERT INTO myTable (column1) values ($2);`

**Comment by robconery** [comment]
I've gotten around this and I'm trying to remember how we did it - @xivSolutions do you remember how we run the batch insert? Isn't it building a big fat query on the fly? I've had this problem pop up before and somehow gotten around it.

**Comment by xivSolutions** [comment]
@robconery - yep - dynamically building one big singe `insert` with multiple value groups. We don't have that here in Massive within a transaction (yet). But I think it's worth adding.

You should be able to build one insert which handles all your records, just like he is doing. it is not only more performant, but simpler to write in SQL:

```sql
INSERT INTO myTable (column1, column2, column3) values ($1, $2, $3), ($4, $5, $6) ...($n, $n+1, $n+2);
```

Sadly, this doesn't lend itself to the OP's use-case (using a query from a file), I don't think, because he would need to know in advance how many records he plans to insert. 

BUT, I think we should add an `insertRange(objects)` which will do this in a transaction, like we did in Moebius.

I'll see if I can break away from work long enough to take a swing at that.

**Comment by jnystrom** [comment]
Is this issue the same reason I cannot have a Sql file with:

```
WITH addedRemedy AS (
    insert into remedy(name, description, remedy_value)
    values(, $3, $4) returning *
)
insert into location_remedy(location_id, remedy_id)
select $1, id from added_remedy;

select * from addedRemedy;
```

I am getting an error:

`"cannot insert multiple commands into a prepared statement"`

**Comment by robconery** [comment]
Yeah that's the reason - it's a driver issue. One way around this is to use a function - it would be transactional too.

**Comment by jnystrom** [comment]
@robconery you mean to create a function in postgres directly, and have massive wrap it?  Is this the only way to handle many to many relation inserts?

**Comment by dmfay** [comment]
CTEs are fine; I'm using them in several scripts. I'd bet it's the extra `select * from addedRemedy` that's throwing you (you also appear to be missing `$2` in your `values` statement in the CTE). Try using a `RETURNING` clause instead, or wrapping the insert in another CTE with the main statement being the select from addedRemedy.

**Comment by jnystrom** [comment]
@dmfay you are correct!  It was the additional select statement.  I am doing a `returning *` now, which will give me the id of the new remedy, and I can use that to return the new remedy record.  Thanks!
