### ISSUE TITLE
[suggestion] Where.forTable is quite useful for query generation

### ISSUE THREAD

**Issue by lfreneda** [dmfay/massive-js#289]
Where.forTable is quite useful for query generation, it supports [operators](https://github.com/robconery/massive-js/blob/master/lib/operations_map.js) and is parameterized.

I tried to find a pkg to do it, but I couldn't find any good enough.

Would be great to have it in separated library/package or exposed in some other way.

What you think?

**Comment by robconery** [comment]
If I understand what you're asking (splitting out fx from Massive) I don't really have an urge to support two libraries if I'm honest.

**Comment by dmfay** [comment]
Can't the module be included via `require('massive/lib/where')` already? Maybe not an ideal solution since you might not want all of Massive coming along with, but space is cheap on the server side...

**Comment by lfreneda** [comment]
@dmfay in my case, that was exactly what I did.. But I was wondering that it can be useful outside massive. 

Are you guys okay with a massive subset fork for query generation? :flushed:

**Comment by dmfay** [comment]
Sure! Note that I'm currently working on a rewrite of that module though so it's going to change substantially in the near future.
