### ISSUE TITLE
Table access disappears from massive.connectSync object

### ISSUE THREAD

**Issue by ghost** [dmfay/massive-js#292]
Using a tool from the Jetbrains people called DataGrip (v.  2016.1.1) to manage a Postgres db in Heroku (current ver 9.5.3).  Having successfully set up and connected to all tables including one called 'Users', using Massive (ver 2.3.0).

Using Datagrip, I made some significant changes to the Users structure - - deleted some columns, adding some others, etc.  Now, the db object, created with massive.connectSync **_no longer recognizes the db.users object_** and returns null object errors on simple calls such as db.users.findOne(...).

Except for modifying some columns (I did not touch the primary key field, called id (serial)), nothing else was changed.  All the permissions were as they were before.  I could still access the table through DataGrip.  Nothing I did helped to restore access to db.users.

Ultimately, I created a new table, copied the contents from 'users' into the new table, dropped 'users' and renamed the new table to 'users'.  Access through Massive was restored.

This concerns me because I'd hate for it to happen on a production database.  Changes to a database structure are pretty commonplace.

Has anyone else experienced this?  Perhaps you might be able to provide some insight as to how to debug this situation should it occur again.

Thanks.  And thank you for this great project.

**Comment by dmfay** [comment]
You're using `users` and `Users` interchangeably -- are you sure all your references are correct?

**Comment by ProximitySystems** [comment]
Yes, I use only "users", never "Users".  Just a typo here.  All references in the code are correct.

**Comment by robconery** [comment]
Do you have ownership privileges on the DB? Or the ability to run information_schema queries? If the casing is not the issue, then the startup query is not returning any table information is my guess.

**Comment by thejones** [comment]
I have had some strange issues with DataGrip not committing transactions. I am not saying this is the issue but I would say that it is worth checking all of the settings and verifying that DataGrip is not being finicky. In my case, I had issues with a view and ended up needing to drop, close the connection, and recreate the view. This was not involving Massive, just random DataGrip issues.

**Comment by dmfay** [comment]
Closing since sync methods will be deprecated in v3.
