### ISSUE TITLE
Errors using update with compound primary key

### ISSUE THREAD

**Issue by gtebbutt** [dmfay/massive-js#310]
I'm directly calling `db.foo.update(...)` on a table `foo` with a compound primary key (two integer columns), and seeing some rather confusing behaviour: it works fine on my local machine with the dev DB, but as soon as it's moved to staging it returns `Error: duplicate key value violates unique constraint "foo_pkey"`. 

If it were failing in all cases I'd just assume that compound keys are unsupported and find a workaround, but I'm intrigued by the inconsistency. Any thoughts?

**Comment by dmfay** [comment]
What does your update statement look like? With a compound key you might need to use the longer signature -- `db.foo.update(criteria, changes, callback);` -- instead of the shorter version.

**Comment by dmfay** [comment]
No further activity.
