### ISSUE TITLE
saveDoc to save multiple documents at once (like save)

### ISSUE THREAD

**Issue by bguiz** [dmfay/massive-js#318]
If you `save()` an `Array` it inserts multiple rows into the table

If you `saveDoc()` an `Array` it inserts a single row into the table
- this behaviour is understandable, because you might want to legitimately save an array as the root level object in a document
- thus I propose that we have a `saveDocs()` method which _only_ accepts an array, and will insert multiple rows into the table

What do you think of this idea?

**Comment by bguiz** [comment]
There's a [similar issue](https://github.com/robconery/massive-js/issues/301) that was [closed in August](https://github.com/robconery/massive-js/issues/301#event-765227566) by @robconery - new issue because I have an alternative suggestion.

**Comment by dmfay** [comment]
I'm sticking a pin in the document stuff until promises are done but I'd like to keep the number of functions down. I'm not sure it'll be too bad after that though since you could `Promise.all()` and map your array.
