### ISSUE TITLE
select for update?

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#339]
If I have a file that has sql to do a select for update, then next in the code I use the massive `.save()` for that record that should have been locked, does this work as expected?  I would assume I can use the select for update to lock the row(s), then the update using massive would update and release the row lock(s)...is that what would happen?

**Comment by dmfay** [comment]
I wouldn't expect it to, since the lock from `FOR UPDATE` expires when the transaction that creates it ends, and your script will be executed as a self-contained transaction.

**Comment by jnystrom** [comment]
that would be my expectation as well.  Without being able to have multiple commands in a db script, is the idea to be able to wrap commands in a transaction is to write a Stored Proc or function with Massive?

**Comment by dmfay** [comment]
Yes, right now you'd need a Postgres function in order to use `FOR UPDATE` effectively. Moving to promises with v3 will make transaction management much more doable, but that's slow going right now.

**Comment by jnystrom** [comment]
Are you saying that v3 will have transaction support, or that the architecture will allow for transactions at some point?

**Comment by dmfay** [comment]
I can't commit (if you will) to having it in the release, but transaction support has been on my wishlist for a while and I do intend to tackle it at some point.

**Comment by jnystrom** [comment]
@dmfay that is fair.  I am hoping to not have to move to an ORM or write functions... ;)

**Comment by xivSolutions** [comment]
@jnystrom @dmfay - Getting transaction support into Massive is something we would all like to see, and if it is doable in a reasonable way (emphasis on "reasonable") I expect it will appear in the long, long, awaited v3. Sigh. Time.
