### ISSUE TITLE
SearchSync: No Limit and offset possible

### ISSUE THREAD

**Issue by MarcelCremer** [dmfay/massive-js#343]
Hi@all,

in the documentation, I found the example for limit and offset for object queries:

`db.doggies.searchDoc({
  keys : ["name", "owner"],
  term : "Rusty"
  }, {
    limit: 10,
    offset: 20
  }
}, function(err, docs){
  //matching docs returned
});`

If I try to do the same (limit/offset) with db.doggies.searchSync, it doesn't return anything. Do you know if it should be possible to limit / offset FT-Searches or is it by design?

Once again thank you for your great work.

Best Regards
Marcel

**Comment by dmfay** [comment]
It looks like the documentation is in error -- `searchDoc` doesn't apply offset or limit. It probably should at some point!

**Comment by dmfay** [comment]
This is functioning now. Added tests to verify.
