### ISSUE TITLE
Primary key can only be an integer?

### ISSUE THREAD

**Issue by sam3d** [dmfay/massive-js#349]
For my database I have a `users` table with a `username` field of type `varchar(20)`. This is the primary key for that table, and the [massive documentation](http://massive-js.readthedocs.io/en/latest/quick_start/) states that:

> This is because when you query by primary key, Massive understands there can be only one result returned. If you query by other criteria you will have 0 or more results.

Currently I'm having to use `db.users.find({ username: "sam3d" }, ...` which works fine, but it'd be a really nice feature not to have to use a numerical primary key!

**Comment by dmfay** [comment]
Massive supports integer and UUID primary key types, and right now I don't have plans to expand that. I'd caution against using something like a username as a primary key -- if it changes, you have to update all foreign keys referencing your `users` table, and if you miss one, you "lose" data until you go in and fix it. Synthetic keys make life a lot easier.

**Comment by sam3d** [comment]
Thank you very much for the caution! Our users can't change their usernames due to an inherent limitation of the platform we're integrating with, so it seemed a waste to have a separate ID field. Totally understand your reasoning though, perhaps in future.
