### ISSUE TITLE
Can I add keys to the full text .search function?

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#353]
I have a multi tenant db, and would like to specify the tenant and search criteria, is that possible?  Something like:

```
db.users..search({companyId: 123456}, {columns: ['email', 'name'], term: 'rob'}, (err, users) > {
  // get all users that are from company 123456 that have the word 'rob' in their email or name
});
```

**Comment by dmfay** [comment]
Yes, but not quite in that form:

`db.users.search({columns: ['email', 'name'], term: 'rob', where: {companyId: 123456}, (err, users) => {...});`

The `where` is a standard criteria object and you can use operators, `or` arrays, and so on as usual.
