### ISSUE TITLE
descendant_tables.sql not working

### ISSUE THREAD

**Issue by AxGitHubing** [dmfay/massive-js#357]
massive-js/lib/scripts/descendant_tables.sql

is not working. it is not returning any tables. 

so this is not working:
```
//connect to the database. This will load the tables and functions, returning them to the db instance
var db = Massive.connectSync({db : "my_db"});

//query a table
db.my_table.find({name : "Joe"}, function(err,result){
  //result is returned with all records of my_table where the name is Joe
});
```

because _db.my_table_ is undefined.

"massive": "2.6.0"
PostgreSQL 9.6.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit

thx,
Axel

**Comment by dmfay** [comment]
Are you still having problems? Make sure your parent table has a primary key defined; Massive ignores anything without one.

**Comment by AxGitHubing** [comment]
thank you for following up, but looks like it is me having issues with callbacks in node.js. I return the database instance before the tables are created.
But I saw another issue with saveDoc and JSON. After I inserted a JSON a second time, massive added a {"0": <original JSON>}

**Comment by dmfay** [comment]
Could you create a second issue for that and include sample code?

**Comment by AxGitHubing** [comment]
at the moment I am quite busy. No time to check it with some simple sample code. I am sorry.

**Comment by AxGitHubing** [comment]
the issue is that I get the connection to the database with no tables created. then I create the tables and then I pass on the database instance. But the database instance does not habe the reference to the created tables. how can I reload/reconnect/refresh the database object?

**Comment by dmfay** [comment]
You have to call `connect` again. If your schema is static, it's better to manage it separately from your application so it's ready when you start up.

**Comment by AxGitHubing** [comment]
database is in a docker container at the moment. so I need to setup it up on the fly

**Comment by AxGitHubing** [comment]
just wanted to let you know there is no issue with 'saveDoc and JSON'. 
surprisingly the bug was in my code ...
...
...
;-)

**Comment by dmfay** [comment]
Good to know, thanks!
