### ISSUE TITLE
raw query support?

### ISSUE THREAD

**Issue by pablote** [dmfay/massive-js#358]
Sorry if it's a basic question, but I didn't see it mentioned on the docs.

Is there a way for me to just send a full sql statement? The conditions obj is great most of the time, but for a particular complicated query with joins and inner queries I want to send the full query myself. Is it even possible?

thanks

**Comment by dmfay** [comment]
[It's in the docs.](https://massive-js.readthedocs.io/en/latest/simple_queries/#the-simplest-query-inline-sql)

If your query is static it's better for a variety of reasons to [use scripts in the db directory](https://massive-js.readthedocs.io/en/latest/functions/#the-db-directory).

**Comment by pablote** [comment]
missed it, thanks!
