### ISSUE TITLE
The documentation is about v3 but it says: "npm i massive --save", which install version 2.6.1. Where's massive v3?

### ISSUE THREAD

**Issue by andrerpena** [dmfay/massive-js#373]
I can't find instructions for installing massive 3

**Comment by andrerpena** [comment]
I can't find instructions for installing massive 3

**Comment by andrerpena** [comment]
I've just tried 

    npm show massive@* version

Which doesn't show any "next" or "beta" version for 3.

**Comment by andrerpena** [comment]
I can't wait to use it. I've being waiting for native premises since ever. Thank you very much for this. @dmfay . I know Rob was kind of against it.

**Comment by dmfay** [comment]
I wanted another pair of eyes on the docs before I cut a new tag, just to make sure everything in there made sense. Someone was gracious enough to look them over this afternoon, so I'll be doing that in a moment here. Thanks for checking in, and please don't hesitate to reach out if you run into anything!

**Comment by andrerpena** [comment]
@dmfay Thank you very much! I'm super excited with this release.

**Comment by dmfay** [comment]
[It's alive!](https://github.com/dmfay/massive-js/releases/tag/v3.0.0-rc1)

**Comment by andrerpena** [comment]
\o/ Hooraaay! Time to test it!
