### ISSUE TITLE
How do I "terminate" a Massive object?

### ISSUE THREAD

**Issue by andrerpena** [dmfay/massive-js#376]
I have integration tests and between one DB test session and the other I have to terminate the Massive object otherwise I'm getting this warning:

> WARNING: Creating a duplicate database object for the same connection.
>     at new Massive (/home/andrerpena/git/indiejobs/node_modules/massive/lib/database.js:36:22)
>     at module.exports (/home/andrerpena/git/indiejobs/node_modules/massive/index.js:51:11)
>     at _callee$ (/home/andrerpena/git/indiejobs/src/server/helpers/massiveHelper.js:12:12)
>     at tryCatch (/home/andrerpena/git/indiejobs/node_modules/regenerator-runtime/runtime.js:64:40)
>     at Generator.invoke [as _invoke] (/home/andrerpena/git/indiejobs/node_modules/regenerator-runtime/runtime.js:299:22)
>     at Generator.prototype.(anonymous function) [as next] (/home/andrerpena/git/indiejobs/node_modules/regenerator-runtime/runtime.js:116:21)
>     at step (/home/andrerpena/git/indiejobs/src/server/helpers/massiveHelper.js:49:191)
>     at buildMassive (/home/andrerpena/git/indiejobs/src/server/helpers/massiveHelper.js:39:17)
>     at Context.<anonymous> (/home/andrerpena/git/indiejobs/test/integration/setupSession.js:42:9)
>     at callFnAsync (/home/andrerpena/git/indiejobs/node_modules/mocha/lib/runnable.js:368:21)
>     at Hook.Runnable.run (/home/andrerpena/git/indiejobs/node_modules/mocha/lib/runnable.js:318:7)
>     at next (/home/andrerpena/git/indiejobs/node_modules/mocha/lib/runner.js:309:10)
>     at Immediate.<anonymous> (/home/andrerpena/git/indiejobs/node_modules/mocha/lib/runner.js:339:5)

How do I terminate a Massive object?

**Comment by dmfay** [comment]
Short of evicting the module from Node's cache you don't, really. But if you're just trying to run the introspection to load tables/views/etc again, there's a function for that now: `db.reload()`.

**Comment by andrerpena** [comment]
Hopefully this will work. Thank you very much.
