### ISSUE TITLE
massive.connectSync( ) is not a function

### ISSUE THREAD

**Issue by rnoelle** [dmfay/massive-js#378]
Version 3.0 comes up consistently with the above error, whether connecting to a local or remote database. Is there a different way to handle the new version? Connecting on version 2.6.1 works great.

**Comment by dmfay** [comment]
Synchronous functions are no longer supported, and the `connect` function itself no longer exists -- it's all promises all the way. [Connection docs are here](https://dmfay.github.io/massive-js/connecting.html).

If you can use `async`/`await` that's an excellent way to manage promises, or there are libraries like [co](https://github.com/tj/co) which let you `yield` them.

**Comment by rnoelle** [comment]
Thanks so much for the reply!

I was looking at what I assume are the old docs:
https://massive-js.readthedocs.io/en/latest/quick_start/

**Comment by dmfay** [comment]
That's for version 2.x, yeah. I'll see about adding a disclaimer on that side of things. Documentation for v3 is on GitHub Pages.
