### ISSUE TITLE
Expose the db instance through express

### ISSUE THREAD

**Issue by asBrettisay** [dmfay/massive-js#389]
We have been using massive@3 and the best pattern we have found is the one mentioned in the documentation.

Something like
```
massive(connectionString).then(db => {
  app.set('db', db)
})
```

And the endpoint...
```
app.get('/api/stuff', function(req, res) {
  req.app.get('db').stuff.find(...).then(stuff => {
    res.json(stuff)
  })
})
```

My proposal would be to add a `.middleware` method onto massive, so that it could be used like so:

```
const db = massive(connectionString)

app.use(db.middleware())

app.get('/api/stuff', function(req, res) {
  req.db.stuff.find(...).then(...)
})

```

Sorry if this is brash, I really love this tool, this is just an idea I had! I'd be willing to do a PR

**Comment by dmfay** [comment]
I'm happy to hear it's doing well by you! I've thought about expanding that part of the docs into a sort of "cookbook" demonstrating common usage patterns; I still might, if I collect a few more. However, I don't want to introduce framework-specific functionality into the core library: if I start explicitly supporting frameworks, each of those modules is not only dead weight if another (or no!) framework is in use, it's another dependency to keep up with and test.

You've probably got more going on than just Massive -- maybe look into extracting all your `app.use`s and `app.set`s out into a directory of middleware modules. From there, you can use something like [require-all](https://www.npmjs.com/package/require-all) to pull those modules into an array (you'll want your modules to export a priority to sort the array on too) and apply everything to the application object during startup. As an added bonus, this makes testing custom middleware much, much easier.

**Comment by asBrettisay** [comment]
@dmfay excellent, thanks for the response! We appreciate the suggestions.
