### ISSUE TITLE
Any way to insert row WITH a primary key specified?

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#399]
I am wanting to insert a row, the primary key is a UUID, and I am trying to insert a row that has that UUID set in the object to be inserted.  Is there a way I can do this?  It seems like an update will always be tried if an id is specified.

Thanks

**Comment by dmfay** [comment]
Yes: `db.mytable.insert`. `save` is predicated on the assumption that you autogenerate primary keys.
