### ISSUE TITLE
There's an error in the update and save documentation

### ISSUE THREAD

**Issue by andrerpena** [dmfay/massive-js#404]
Here's the `update` example:

![image](https://user-images.githubusercontent.com/1581429/27518195-e23c9b04-59d1-11e7-9fd3-a4c054de9bb0.png)

It says it returns an array in both cases (criteria or object cotaining primary key). But if you pass an object containing a primary key, the result is not an array, it's just one object. The same applies for `save`.

This error must have influenced the person who created the [TypeScript definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/massive/index.d.ts), because there, `update` and `save` always return an array, as the documentation says.

I'm having a hard time trying to figure out the best way to fix the typings. IMHO, it would be best if the return types were consistent, e.g, always returning an array as documented.

**Comment by vitaly-t** [comment]
I'm guessing, the error comes from here: https://github.com/dmfay/massive-js/blob/master/lib/database.js#L165

`queryResult.any` mask would result in array always, while `queryResult.one | queryResult.none` results in either `null` or one object.

**Comment by andrerpena** [comment]
Thanks for the reply. I assume this `options` object must be from the pg driver.

In the title, I stated this is an error with the documentation but I'm not even sure. Maybe the way it is in the docs is the way it's supposed to work.

People working with regular JavaScript can adapt more easier. If an array is returned you just treat it as an array, but when there's TypeScript, for example, things get trickier.

**Comment by dmfay** [comment]
`save` is a very (very!) thin wrapper on `update` and `insert`, which is also affected -- given an object it returns an object, given an array it returns an array. This is how it worked in v2, and from a convenience perspective it's really annoying to have to unwrap an array after giving Massive a single object to write. So while I'm sympathetic to the consistency argument I'm inclined to call this a documentation error.

I've never worked with TypeScript, but it looks like it's possible to declare multiple return types for a function; would something along the lines of `insert(data: any[] | object): Promise<T> | Promise<T[]>;` be appropriate?

**Comment by dmfay** [comment]
I've corrected the documentation and raised an issue with DefinitelyTyped.
