### ISSUE TITLE
Error on require('massive')

### ISSUE THREAD

**Issue by Atulvermaon18** [dmfay/massive-js#406]
On using "var Massive=require("massive");" . I am getting error

```
exports = module.exports = (connection, loaderConfig = {}, driverConfig = {}) => {
                                                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/shoppertreat/pgsql/index.js:1:75)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

**Comment by vitaly-t** [comment]
Looks like your Node.js is earlier than 6.x, and according to [travis.yml](https://github.com/dmfay/massive-js/blob/master/.travis.yml), Massive.js doesn't support earlier Node.js

**Comment by dmfay** [comment]
If it were just using default parameters I could see expanding backward compatibility, but I'm looking at doing stuff with proxies and there's no way to make that work with anything older than 6.x. If that doesn't pan out I'll take another look at it, but I don't want to add 4.x compatibility only to take it out again shortly afterward. In the mean time, I've updated the readme.

Node does move quickly but 6.x is over a year old and two major versions behind current at this point, so I don't think it's that big a problem.

**Comment by Atulvermaon18** [comment]
Yeah It was a Node version Issue. when I upgraded it worked well but I am not able to connect to Postgres getting error 

`(node:27380) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): error: password authentication failed for user "postgres"
`

**Comment by dmfay** [comment]
Make sure the `postgres` user has a password (it is locked down and doesn't have one by default) and that you're providing the right one to Massive, or create another user in Postgres to connect as and use its credentials instead. The latter course of action is much safer -- connecting as `postgres` is like doing everything as `root`.
