### ISSUE TITLE
How do I "insert" a record, with a column being the result of a function call?

### ISSUE THREAD

**Issue by andrerpena** [dmfay/massive-js#411]
Hi,

I'm using POSTGIS and I need a column to be set as 

```
ST_SetSRID(
        ST_MakePoint(
            longitude,
            latitude,
        4326)
```

during `insert`. How can I do that?

Thanks!

**Comment by vitaly-t** [comment]
You can use the standard `$1` variables or Named Parameters `${name}`, if you wrap your type into a [Custom Type](https://github.com/vitaly-t/pg-promise#custom-type-formatting):

```js
function srid(lng, ltd) {
    return {
        _rawDBType: true,
        formatDBType: () => 'ST_SetSRID(ST_MakePoint(' + lng + ', ' + ltd + ', 4326)'
    };
}
```

**Comment by andrerpena** [comment]
@vitaly-t , thank you very much.

**Comment by vitaly-t** [comment]
@andrerpena Please note that when Massive updates its driver to [v6.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.5.0), there will be a breaking change for the [Custom Type Formatting].

[Custom Type Formatting]:https://github.com/vitaly-t/pg-promise#custom-type-formatting
