### ISSUE TITLE
Is there a way to create the db connect sync instead of async?

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#412]
I am currently using `Massive.connectSync()` to make sure the connection happens before I start using it.  Is there any version of sync connection in the new v3 api?

**Comment by dmfay** [comment]
No. If you're using Node 7 or 8 you can use `async`/`await`, or otherwise a flow control library like [co](https://github.com/tj/co) to manage promises with a synchronous idiom, but it's gone for good from Massive itself.

**Comment by jnystrom** [comment]
ok, I was making the connection in the constructor of my repository class, and I cannot make a constructor `async`, as I am using Typescript with async/await.

**Comment by dmfay** [comment]
You'll want to pass a connected instance in, add an asynchronous init function to your repository, or since it's just the connection, [deasync](https://github.com/abbr/deasync) it yourself.

**Comment by jnystrom** [comment]
yup, going to stick with v2.x until I have time to redo

**Comment by jnystrom** [comment]
OK, so I am getting around to upgrading.  I have upgraded to v4.0.  I have changed the `Massive` connection call to use `deasync` like you suggested.  

All of a sudden I am not getting TONS of these errors:

```
Creating a duplicate QueryFile object for the same file - 
    /Users/johnnystrom/dev/remedy/coreApi/node_modules/massive/lib/scripts/tables-whitelist.sql
    at loader.queryFiles.files.reduce (/Users/johnnystrom/dev/remedy/coreApi/node_modules/massive/lib/database.js:157:43)
    at filesPromise.$p.then.files (/Users/johnnystrom/dev/remedy/coreApi/node_modules/massive/lib/database.js:156:38)
```

I am using the repository pattern and have multiple repositories that inherit ( using Typescript) reference my MassiveRepository class.  This all worked great with v2.X, now I am getting these errors along with:

`error: too many connections for role <db connection name>`

ideas?
