### ISSUE TITLE
How to use schemas in the API

### ISSUE THREAD

**Issue by jakewilson801** [dmfay/massive-js#422]
If I run raw sql it works just fine IE `select * from my_schema.table_name` but if I run `instance.my_schema.table_name.findOne(...` it doesn't work. I couldn't find anything on schemas when I searched the docs. 

Help!??

**Comment by dmfay** [comment]
You're doing it right ([this](https://dmfay.github.io/massive-js/connecting.html) is the relevant page in the docs). Two questions:

* What is "doesn't work": no results, an error? Is there a stack trace?
* Does your table have a primary key defined?

**Comment by jakewilson801** [comment]
Thanks for the speedy response. 

This is the code 
```
```
error = `TypeError: Cannot read property 'findOne' of undefined`

**Comment by jakewilson801** [comment]
Thanks for the quick response. I was just being a dumb dumb. Closing now...
