### ISSUE TITLE
Promise refactoring for `undefined`.

### ISSUE THREAD

**Issue by vitaly-t** [dmfay/massive-js#423]
There is a number of considerations one has to make when converting a callback interface into promises.

One such consideration is to get rid of ever returning/resolving `undefined` by any of the methods. Unlike regular callbacks, within the promises realm it is considered an anti-pattern, and many libraries, including the proverbial Bluebird will complain about such cases.

Here's example in your code: https://github.com/dmfay/massive-js/blob/82fb9bc6815e943a1006c72c7084b2b53602790b/lib/queryable.js#L118

Once upon a time, pg-promise also resolved with `undefined` from method `oneOrNone` (when no record found), and after finding all the issues with that, I did the breaking change and replaced it with `null`. It was more than a year ago.

I suggest that you refactor the library in the same manner, make sure none of its methods ever resolve with `undefined`, do `null` instead :wink:

P.S. Why it is considered an anti-pattern: In the promise chain `undefined` means `failed to handle`, or `empty handler`, which in itself is an anti-pattern. So in order for a promise library to be able to tell the difference, returning `null` is the solution.

**Comment by vitaly-t** [comment]
P.S. Breaking my head over how to support the multi-result sets introduced in `node-postgres` 7.0.0... 😕

**Comment by dmfay** [comment]
Looks like that was the only one, & that's taken care of.

**Comment by vitaly-t** [comment]
Well done! ;)
