### ISSUE TITLE
Issue inserting array of BIGINT

### ISSUE THREAD

**Issue by tamlyn** [dmfay/massive-js#424]
Given this table

    CREATE TABLE testing_table (
      id      SERIAL PRIMARY KEY,
      number  BIGINT,
      numbers BIGINT []
    );

When I run 

    await db.testing_table.insert({number:'123'})
    await db.testing_table.insert({numbers:['234']})

The first query succeeds but the second fails with 

    error: column "numbers" is of type bigint[] but expression is of type text[]

I would expect the automatic casting to apply to arrays too. This could be an upstream issue with `pg-promise`.

**Comment by vitaly-t** [comment]
pg-promise doesn't do any automatic casting, because it doesn't work with the database structure, it only executes queries.

**Comment by dmfay** [comment]
My first guess was something all the way up the chain with node-pg, but no, this works:

```
const { Client } = require('pg');
const client = new Client();

(async () => {
  await client.connect();

  const res = await client.query('insert into bigints (one, many) values ($1, $2)', ['111', ['222', '333']]);
  console.log(res);
  await client.end();
})();
```
```
LOG:  execute <unnamed>: insert into bigints (one, many) values ($1, $2)
DETAIL:  parameters: $1 = '111', $2 = '{222,333}'
```

A prepared statement from psql works too:

```
[local] dian#dian= prepare ins (bigint, bigint[]) as insert into bigints (one, many) values ($1, $2);
[local] dian#dian= execute ins('111', '{"222","333"}');
```
```
LOG:  statement: execute ins('111', '{"222","333"}');
DETAIL:  prepare: prepare ins (bigint, bigint[]) as insert into bigints (one, many) values ($1, $2);
```

whereas from the Massive REPL, going directly to pg-promise doesn't:

`db.instance.query('insert into bigints (one, many) values ($1, $2)', ['111', ['222', '333']]);`
```
LOG:  statement: insert into bigints (one, many) values ('111', array['222','333'])
ERROR:  column "many" is of type bigint[] but expression is of type text[] at character 48
HINT:  You will need to rewrite or cast the expression.
STATEMENT:  insert into bigints (one, many) values ('111', array['222','333'])
```

It looks like pg-promise is formatting array values for prepared statements [here](https://github.com/vitaly-t/pg-promise/blob/aba25680aa8cc469a7fd2c9eb1a39bbd0e75440d/lib/formatting.js#L97), in a way that Postgres can't automatically coerce to the correct type.

**Comment by vitaly-t** [comment]
pg-promise escapes every array according to the proper PostgreSQL syntax, of which there are two:

* the old/legacy approach was to use `{value, value,...}`
* new new one since 9.0 is to use `array[value, value,...]`

And while it is using the second approach, it separately escapes each value in the array according to its type.

@tamlyn you have 2 options to do it right:

* make sure the array contain numbers, and not strings
* or execute the query with the type cast of `::bigint[]`

**Comment by tamlyn** [comment]
Thanks both. So just to recap: this behaviour is actually a feature of Postgres because

    INSERT INTO bigints (one) VALUES ('123');         -- works
    INSERT INTO bigints (many) VALUES ('{123}');      -- works
    INSERT INTO bigints (many) VALUES (ARRAY['123']); -- fails

@vitaly-t I'm taking the fourth option which is to change the column type to `TEXT[]`! They're Twitter IDs which are too big for JavaScript numbers so need to be loaded as text anyway.

**Comment by vitaly-t** [comment]
@tamlyn that's probably the best solution :) as working with 64-bit numbers in JavaScript is awkward, and best is avoided, if possible ;)

**Comment by tamlyn** [comment]
I see that Massive supports [casting in criteria objects](https://dmfay.github.io/massive-js/criteria.html#casting). Any thoughts of supporting explicit casts on insert? I imagine another option to `insert()` something like `{cast: {many: 'bigint[]'}}` (for the above example). That would enable Vitaly's second option above without custom SQL.

**Comment by juan-quiver** [comment]
As massive.js isn't casting on insert / update just yet, what you can do is turn your array into the second format @tamlyn mentioned, like:

`await db.testing_table.insert({numbers: `{${numbers.join(',')}}` })`

**Comment by dmfay** [comment]
@tamlyn I missed your comment about using options to allow casting per-field -- that'd be neat!
