### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by spikeon** [dmfay/massive-js#429]
Could you please put the "no results found" response for queries into the documentation?  I know that find() is an empty array ( however, this should also be put in the documentation to spell it out for people ), but is findOne() undefined, false, null, an empty object, or something else?

Thanks.

**Comment by dmfay** [comment]
oh, good thought! If you want to go through some of it and put up a pull request that'd be great, or I'll get to it in a little while.

**Comment by spikeon** [comment]
I have another item to add to this:

Your examples don't include basic use cases. For example, to get all items from a table without filtering them at all, do I have to use `.find({ id : "*" })` or `.find({})` or `.find()` or can i just use `db.table.then()` or is there a `db.table.list()` function I don't know about?

**Comment by spikeon** [comment]
I'm sorry, I just took a look at the changes in the lib folder.  I should've been more specific.  I meant the README.md documentation and examples, for both the empty result and for this.  I should've looked at the jsDoc to see if the answer was there before, but now I know.  However, still these things should probably still be added to the README.md.

**Comment by dmfay** [comment]
I've actually been thinking about trimming the readme down to remove most of the detailed documentation, since having that in two places is more work than it's really worth.

**Comment by spikeon** [comment]
I agree that duplicating efforts is tiring, however, perhaps at the bottom you can do a bunch of example calls, like font-awesome is doing in their alpha build documentation.  

For example: 

**Find**
`
db.site.find(); // Returns an array of all sites
db.site.find("*"); // Returns an array of all sites
db.site.find(1); // Returns an array containing the site with id 1
db.site.find({url : "google.com"}); // Returns an array of sites with the url "google.com"
...
`

**Comment by dmfay** [comment]
Something like that, yeah. I'm not just going to truncate it with a link to the main docs :)

**Comment by spikeon** [comment]
Oh, I'm an idiot.  Yes, put in a link to the main docs.  How about a big bold flashing link so idiots like me know it exists. 

Sorry I wasted your time.  Haha.
