### ISSUE TITLE
All values from calling SQL in a file return strings?

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#434]
I have fields I am returning that are numbers, but when I call the `db.<filename>`, the numeric values are strings.  Is this expected?

**Comment by dmfay** [comment]
`bigint`/`int8`s I'm guessing? Yes. JavaScript `Number`s only go up to 53 bits, so the driver returns 64-bit integers from Postgres as strings. You can use [pg-types](https://github.com/brianc/node-pg-types) to override this behavior if you know you're never going to need numbers that big.

**Comment by vitaly-t** [comment]
The following explains it nicely: https://stackoverflow.com/questions/39168501/pg-promise-returns-integers-as-strings

**Comment by jnystrom** [comment]
My data are stored as Decimals in the DB....guessing it is the same issue.

**Comment by vitaly-t** [comment]
> My data are stored as Decimals in the DB....guessing it is the same issue.

Yes, as there is more than one way to present those values in JavaScript, the values are provided as strings, to avoid ambiguity.

**Comment by cjevning** [comment]
@dmfay the suggested fix no longer parses bigints into strings as of version 4.1.0, not sure if this is related to massive or pg-promise

**Comment by vitaly-t** [comment]
@cjevning This is usually pertains to the client-side who decode to use or not to use custom parsers :wink:

Surely nothing changed in pg-promise or the underlying driver for that.

**Comment by dmfay** [comment]
Bigints turning into strings was the _undesired_ behavior here and the fix involved using custom parsers to ensure they stayed numeric. Could you please clarify?

**Comment by cjevning** [comment]
whoops sorry, late night typo. i meant that on massive 4.1.0 or later, my bigint's are always strings rather than being parsed, with no changes to the parsing code
```
const types = require('pg').types;
types.setTypeParser(20, val => parseInt(val, 10));
```

**Comment by dmfay** [comment]
That is weird! However, this testcase works fine against v4.2.0:

```
  it('changes types', function* () {
    const stringCount = yield db.run('select count(*) from products');

    assert.typeOf(stringCount[0].count, 'string');

    types.setTypeParser(20, parseInt);

    const intCount = yield db.run('select count(*) from products');

    assert.typeOf(intCount[0].count, 'number');
  });
```

so I'm guessing it's something in your code. Are you perhaps changing the type parser before you initialize Massive? I have no idea why that would have worked prior to v4.1.0 but I think it'd explain it _not_ working.

**Comment by cjevning** [comment]
I was changing the type parser before initializing, but now I moved that code to after initialization but the strings still won't parse in >= 4.1:
```
  // connect to Massive and get the db instance.
  massive(dbConfig[environment])
    .then((db) => {
      const types = require('pg').types;
      // Converts pg values of type bigint to js ints
      types.setTypeParser(20, val => parseInt(val, 10));

      // Set a reference to the massive instance on Express' app
      app.set('db', db);

      //other init code, loggers and such not touching db

      app.listen(port, (listenError) => {.....
```

**Comment by dmfay** [comment]
Have you tried `rm -rf`ing your `node_modules` and `package-lock.json` (if you have one) and reinstalling your dependencies? I'll occasionally edit something in there and forget to change it back.

If that didn't or doesn't change anything, you could try cloning the repository and seeing if _you_ can run that testcase on your local system just to rule out anything exceptionally bizarre.

**Comment by cjevning** [comment]
`rm -rf` didn't do it, until I restarted my computer ¯\_(ツ)_/¯ now with the code moved to after the db init it works as expected again, thank you!

**Comment by dmfay** [comment]
oh wow, that's a new one :rofl: At least it's working!
