### ISSUE TITLE
Default schema other than "public"

### ISSUE THREAD

**Issue by tamlyn** [dmfay/massive-js#438]
For my integration tests I want to set [`search_path`](https://www.postgresql.org/docs/current/static/runtime-config-client.html) to `pg_temp`. This gives me a unique schema per connection so each of my tests runs in isolation and data gets cleaned up automatically. So far so good.

But during introspection Massive assumes the default schema is `public` so doesn't pick up the tables in `pg_temp`. However if I create the necessary tables in `public` the introspection works but the queries are then run against the data in `pg_temp` - which is a pretty weird state of affairs!

Looking at the code it seems that it should be possible to run `SELECT current_schema` and store that somewhere to use instead of hard coding `public`. However I appreciate this is an edge case type scenario and I'm not sure if it's something you would like to add to the library.

**Comment by dmfay** [comment]
I'm not sure I'm following your process completely. I know `pg_temp` is per connection; are you connecting Massive without a pool, creating structure through scripts, and using `reload` to scan it all in?

I'd be open to a config option to set the default search path and override `public`, but I don't know if that's what you intend.

**Comment by tamlyn** [comment]
Yes, that's what I'm doing. 

I would say it's better to introspect the search path from the DB rather than have a config option for it. It's an extra request but should be super quick. Agree?

**Comment by dmfay** [comment]
ah, I haven't had to do much with search paths, I didn't realize it could be set more permanently. We should respect the db/user setting, so that sounds good!
