### ISSUE TITLE
Passing the value null in for a parameter is throwing an error

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#443]
If `$2` is null at runtime when the function is called with the following sql, it fails with massivejs saying it cannot determine the data type of parameter `$2`.

example SQL:
```
select distinct loc.name
from agent as ag
inner join agent_location as al on al.agent_id = ag.id
inner join location as loc on loc.id = al.location_id
inner join company as c on c.id = loc.company_id
where c.hostname = $1 and $2 is null or (ag.id = $2);
```
Error:

![screen shot 2017-08-10 at 1 46 13 pm](https://user-images.githubusercontent.com/1293142/29183915-5d0b4c3a-7dd2-11e7-91ed-5a32d45c402b.png)

**Comment by dmfay** [comment]
That's a Postgres error. You can try preparing the statement yourself in psql: `prepare mystatement as select...` will raise the message you mention.

If you switch the order around to `where c.hostname = $1 and (ag.id = $2 or $2 is null)`, it's able to infer the type.
