### ISSUE TITLE
Discussion: Nested joins (objects/arrays) - proposal

### ISSUE THREAD

**Issue by robertrossmann** [dmfay/massive-js#453]
It was discussed previously that support for nested objects and arrays through joins would be great so that post-processing the results should not be necessary.

### Example

Here's an example data structure that many people would love to see as a direct query resultset:

```js
// Imaginary user information resultset returned from `massive.run()`
[
  {
    id: '123',
    email: 'test@test.com',
    // Nested object structure
    address: {
      street: 'Imaginary Street 123',
      city: 'Imaginary town'
    },
    // Nested array with object structures
    purchases: [
      {
        id: '123',
        item: 'Shoes',
      },
      // ...
    ]
  },
  // ...
]
```

### The problem

- SQL does not support this kind of structure in the resultset - it's always just a single set of rows with columns (ie. a flat structure).
- One can perchance achieve this structure with various `json` functions and transformations, but it requires careful SQL tuning and the ergonomics of such SQL are not optimal
- Other solutions involve providing out-of-band hinting (ie. schema) as to how to transform the results which, as I understand, massive maintainers are (understandably) strongly against

### The solution

Since the developers best understand their data structures while writing the SQL, we can provide (optional) support for hinting directly through the SQL being executed.

#### Summary

In `select` clause, fields separated with `.` (dot) will be parsed as nested object. Fields separated with `/` (slash) will be parsed as nested array.

#### Example

Let's say that to achieve the resultset written above, one would provide the following SQL query to `massive.run()`:

```sql
select
  users.id as id,
  users.email as email,
  addresses.street as "address.street",
  addresses.city as "address.city",
  purchases.id as "purchases/id",
  purchases.item as "purchases/item"
from users
left join purchases on users.id = purchases.user_id
left join addresses on users.id = addresses.user_id;
```

massive now has enough information to know how to transform the resultset.

This feature could be implemented "on-demand", ie. a switch needs to be specified in order to activate this functionality.

Also, this will not work for streaming resultsets because there is no indication that the primary object is now complete.

Let me know what you think about it! If you like it, I might be able to put a PR together adding this feature. Thanks!

**Comment by vitaly-t** [comment]
A related example: [get JOIN table as array of results with PostgreSQL/NodeJS](https://stackoverflow.com/questions/39805736/get-join-table-as-array-of-results-with-postgresql-nodejs)

**Comment by dmfay** [comment]
I should say I'm not by any means dead set against using ad-hoc schemas as in my example for #263. I'd prefer to avoid it if possible, of course, but easy decomposition is so much more useful than strict adherence to no-independent-schemas-not-ever that if it's a choice between the two the first one wins hands down. What I _don't_ want is a solution that requires handwritten SQL; I think that really limits how much use people will get out of it. Something like this needs to be accessible when eg using `db.find` against a multi-table view in order to be most effective.

**Comment by dmfay** [comment]
I wound up doing more or less what I was talking about in #263. `options.decompose` takes a schema and will cut your resultset to fit.
