### ISSUE TITLE
MassiveJS returning wrong timezone

### ISSUE THREAD

**Issue by sam3d** [dmfay/massive-js#461]
This is really weird, and I can't figure out what's happening. I have a postgresql database and a server on my local machine. I'm on `GMT (BST)` timezone, so everything in the database in `UTC` should look one hour behind where I'm at (as my local machine is set to that timezone):

<img width="332" alt="screen shot 2017-09-10 at 14 40 52" src="https://user-images.githubusercontent.com/8385528/30249531-29e5e5aa-9636-11e7-90c8-f65db38331ca.png">
<img width="413" alt="screen shot 2017-09-10 at 14 41 11" src="https://user-images.githubusercontent.com/8385528/30249532-2a04097c-9636-11e7-8aea-4ed6f025f4a4.png">

Which, for all intents and purposes, it does, when I query it ordinarily. However, when I run a massive-js query to get the exact same result set (with either `massive.run()` or `massive.orders.find()`), it returns the timezone one hour earlier than _that_:

```javascript
db.run("select start_slot, end_slot from orders where user_id = ${ id }", { id: req.user }).then(orders => res.json({ orders }));
db.orders.find({ user_id: req.user }).then(orders => res.json({ orders }));
```

Both return:

```json
{
    "orders": [
        {
            "start_slot": "2017-09-11T07:00:00.000Z",
            "end_slot": "2017-09-11T08:00:00.000Z"
        },
        {
            "start_slot": "2017-09-11T07:00:00.000Z",
            "end_slot": "2017-09-11T08:00:00.000Z"
        }
    ]
}
```

It seems like, because of the `Z`, these dates should be in `UTC` instead of what I think is `UTC-1`. Any idea on what's happening or how to fix it would be _massive_ ly appreciated (sorry). Thank you!

**Comment by dmfay** [comment]
When you're dealing with fixed points in time, you should _always_ use `timestamp with time zone` aka `timestamptz`. [This StackOverflow answer](https://stackoverflow.com/questions/9571392/ignoring-timezones-altogether-in-rails-and-postgresql/9576170#9576170) goes into why.

**Comment by sam3d** [comment]
Thank you for the help!
