### ISSUE TITLE
Insert depends on key order in objects

### ISSUE THREAD

**Issue by markgeraty** [dmfay/massive-js#465]
When inserting an array of objects, it is assumed all of the objects in the array were defined with their properties in the same order.  For example (walking through [insert.js](https://github.com/dmfay/massive-js/blob/master/lib/statement/insert.js#L30-L31):

```javascript
// this.records = [{ a: 'apple', b: 'banana' }, { b: 'bear', a: 'aardvark' }];

this.columns = _.map(_.keys(this.records[0]), key => `"${key}"`);

// this.columns = [ '"a"', '"b"' ]

this.params = _.flatten(this.records.map(r => _.values(r)));

// this.params = [ 'apple', 'banana', 'bear', 'aardvark' ]
```

Here, the values for column `a` and `b` have been swapped in the second record, resulting in our table having these records:

 a  |  b 
--- | ---
apple | banana
bear  | aardvark

**Comment by markgeraty** [comment]
Just reading this again it sounds like a far-fetched scenario, but we ran into it pretty innocently when combining existing records fetched from the database via massive and returned to the client, then appending new records from a separate source and writing them back to the server.

@failociraptor

**Comment by dmfay** [comment]
yeah, that's too fragile. Thanks for the report!
