### ISSUE TITLE
Cannot update/insert empty array since 3.x

### ISSUE THREAD

**Issue by btd** [dmfay/massive-js#468]
Because pg-promise format arrays as array[] - postgres require for such literals explicit type casting.
I created issue in https://github.com/vitaly-t/pg-promise/pull/400.
But it seems more relevant place is massvejs issues

**Comment by vitaly-t** [comment]
Clarification: explicit type is required when trying to pass in an empty array, because in this case the type cannot be inferred automatically.

**Comment by dmfay** [comment]
Yeah, that's going to need fixing. I think strictly speaking the Right Way would be to record column types on init and cast, but the possibility of custom types makes me a little nervous about that approach.

There is also a simpler workaround than what @vitaly-t suggested in the other ticket, btw: just insert `{array_field: '{}'}` and Postgres will parse it :smile:

**Comment by vitaly-t** [comment]
True, that's like re-implementing that `wrap` function to just this:

```js
function wrap(array) {
    return array.length ? array : '{}';
}
```

which will work the same :smile:

**Comment by btd** [comment]
@dmfay Thank you!

**Comment by vitaly-t** [comment]
@dmfay  Oh, wow, I was actually still considering the change, but you went and did it on your side. I thought there was going to be a discussion on how best to approach it :smile:

**Comment by dmfay** [comment]
I mean, you could add a fallback to the legacy `{}` yourself and I could take it out of Massive, but it's kind of six of one half a dozen of the other :wink: An introspection-based solution would have to be Massive anyway, but right now I think that's more trouble than it's worth.

**Comment by vitaly-t** [comment]
As per here: https://github.com/vitaly-t/pg-promise/pull/400

It won't work for nested empty arrays. Not to worry, just seat back and wait for pg-promise 6.7.1

**Comment by vitaly-t** [comment]
After much huffing and puffing, [version 6.7.1](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.7.1) is finally out.
