### ISSUE TITLE
New JSON traversal doesn't work in order option

### ISSUE THREAD

**Issue by cjevning** [dmfay/massive-js#474]
The new JSON traversal methods work well in the criteria object, however they don't seem to work when used in the query options, for example I have a JSONB column `timing` and can select `timing.claim` but if I wanted to order by it, using `timing.claim` results in a `42P01` error from postgres, while using the standard PG form (`timing->>'claim'`) works as expected.
```
order: [{ field: "timing.claim", direction: 'desc' }]    // doesn't work, 42P01
order: [{ field: "timing->>'claim'", direction: 'desc' }]    // works fine
```
Not sure if this is a bug or if this is expected behavior, although if it's the intended behavior it may be worth making that more clear in the documentation.

**Comment by dmfay** [comment]
Yeah, the idiomatic JSON path processing is only in the `WHERE` clause generation right now. It'll be a bit messy to break that out and apply it to `ORDER BY`, but I've been meaning to revisit sorting for a while now. Consider it a bug at the moment, but at least the direct way still works there.

**Comment by cjevning** [comment]
:+1: sounds good, thanks!

**Comment by dmfay** [comment]
Reopening til it's fixed. I should put a note about that in the contributing guide...
