### ISSUE TITLE
Missing join tables in db.tables

### ISSUE THREAD

**Issue by brad-decker** [dmfay/massive-js#476]
So, to give a high level overview of our table structure. We have main tables that are capitalized. 'Users' and 'Lifestyles' among others. We also have join tables such as 'userLifestyles'. Some, but not all of, the join tables are missing when we run massive. So if we were to do:

```js
  db.userLifestyles
```

we get undefined. We can query that table just fine without using the massive helper. Also if I loop through the values of db.table and console.log the path all of the tables that are camelCase (join tables) appear twice. Note in the clip below i'm toLowerCase()'ing to group like items. 

```
db.tables
  .filter(t => t.schema === 'public')
  .map(t => t.path.toLowerCase())
  .sort()
  .forEach(t => console.log(t));

agentproperties
agentproperties
businessdeveloperproperties
businessdeveloperproperties
[...]
```

Overall there are three tables missing from massive. What would cause this to happen? Tagging the engineer on our team who originally discovered the issue which lead to this discover @arilfrankel

**Comment by dmfay** [comment]
Your join tables probably don't have primary key constraints defined. Some table functionality depends on primary keys so Massive ignores tables without them.

**Comment by AriLFrankel** [comment]
Thanks for this, @dmfay

What sorts of functionality depend on primary keys?

Sounds like a quick solution for us would be to simply add primary key indexes to the join tables that don't have them already.

**Comment by brad-decker** [comment]
This was definitely the issue, @dmfay thanks for the assist !
