### ISSUE TITLE
Singleton connection

### ISSUE THREAD

**Issue by jaimesangcap** [dmfay/massive-js#500]
I think the suggested way to access the db connection is by using `.then` and set it to the `app` (in case of express). Is it possible to have a way to get a singleton connection? I think it can be used if you want to abstract database operations in their own methods like:

```
import db from './db'

export createTask = async (task, db) => {
  return await db.saveDoc('tasks', task)
}
```

then I can use this on request handler of the app
```
router.post('/tasks', async ctx => {
  const task = await createTask( ctx.request.body)
  ctx.status = 201
  ctx.body = task
})
```

**Comment by dmfay** [comment]
It looks like you're using Koa? The corresponding technique to using the Express `app` is to put it on the context:

```
  app.context.db = await massive(config.connection);
```

Then you can have middleware/routes which `await ctx.db.saveDoc` and pass `ctx` to shared functionality.

You could do what you're suggesting and have a separate module which initializes and returns an instance of Massive act like a singleton; just export a function which checks a module-level variable. That's only something I'd consider if I needed to access the database independent from the server application, but `createTask` sounds like it could be that.

**Comment by jaimesangcap** [comment]
Thank you for responding. Yes I'm using Koa on my example. I think the `async/promise` makes it tricky to make a single, no? Even if I have to make `getDatabase` lets say, I need to do the operations in `await/then` part.

```
const getDatabase = () => {
    return await massive('connection')
}

export createTask = async (task, getDatabase) => {
  return await getDatabase().then(db => db.saveDoc('tasks', task)
}
```

Any thoughts on this one?

**Comment by vitaly-t** [comment]
The underlying driver `pg-promise` supports it fully...

```js
db.instance.task(t => {
    // t = task context to execute all queries against
})
.then(data => {})
.catch(error => {})
```
See [Tasks](https://github.com/vitaly-t/pg-promise#tasks).

Plus, there is a manual singleton for special cases, like `LISTEN/NOTIFY`, see [connect](http://vitaly-t.github.io/pg-promise/Database.html#connect).

**Comment by jaimesangcap** [comment]
@vitaly-t thanks for the reference. I was hoping to have it with massive though

**Comment by vitaly-t** [comment]
@jaimesangcap b.t.w., if your queries do not involve JSON, then you won't need Massive support of it ;)

**Comment by jaimesangcap** [comment]
@vitaly-t by JSON you mean stored as Documents (jsonb)? Unfortunately I'm using massive as document store.

**Comment by vitaly-t** [comment]
>  by JSON you mean stored as Documents (jsonb)

Yeah :)

**Comment by dmfay** [comment]
@jaimesangcap at the simplest level you put your database init stuff in a separate module that looks like this:

```
const massive = require('massive');

let db;

exports = module.exports = () => {
  if (!db) {
    db = massive();

    return db;
  }

  return Promise.resolve(db);
};
```

Then you get an instance in your async function like this:

```
const getInstance = require('./getInstance');

(async () => {
  const db = await getInstance();

  console.log(db.tables.map(t => t.name));
})();
```

Strictly speaking this isn't a capital-S Singleton as handed down from on high by the GoF but it'll do.

**Comment by jaimesangcap** [comment]
@dmfay cool thank you. Looks the same of what I have now. I think I should close this one already

**Comment by robertrossmann** [comment]
A little bit late to the party, but you could also export a singleton using something along the following:

```js
const Database = require('massive').Database
const database = new Database('...')

// This returns a Promise, sooo... Make sure you do not use
// the instance before this has been resolved!
database.reload()

module.exports = database
```
