### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by sam3d** [dmfay/massive-js#502]
Not an issue, just wanted to say thank you so much for creating such an awesome library. I use it extensively in almost all of my projects and it saves so much time and headache.

You're awesome, keep up the great work! 😄 🎉 🎉 🎉

**Comment by dmfay** [comment]
aw thanks :grin: It was Rob's originally so credit where it's due there, I just took over for v3 and onward :wink:

**Comment by sam3d** [comment]
*maintaining then 😉
