### ISSUE TITLE
Types unsupported by the query method

### ISSUE THREAD

**Issue by vitaly-t** [dmfay/massive-js#503]
https://github.com/dmfay/massive-js/blob/ae00a50b13bc7192801603da8a86e3ab4bad136e/lib/database.js#L203

There are other types supported for parameter `query` within `pg-promise`:

* [PreparedStatement](http://vitaly-t.github.io/pg-promise/PreparedStatement.html) = `{name, text, values}`
* [ParameterizedQuery](http://vitaly-t.github.io/pg-promise/ParameterizedQuery.html) = `{text, values}`
* `function` that returns the query string/object

---

Dunno if this important in the context of this library, so if not - feel free to close it. It's just a checkpoint :wink:

**Comment by dmfay** [comment]
yeah, none of those are really necessary here, but thanks for the heads up!
