### ISSUE TITLE
Feature request: allow raw sql queries to take options

### ISSUE THREAD

**Issue by hjsu** [dmfay/massive-js#507]
I think it'd be neat for db.run to be able to take in options, allowing for the use of decompose on raw queries.

**Comment by dmfay** [comment]
`db.query` will already do this. I need to document that then probably deprecate `db.run`.

**Comment by hjsu** [comment]
Submitted a pr: https://github.com/dmfay/massive-js/pull/508

**Comment by dmfay** [comment]
all done here.
