### ISSUE TITLE
default Id field can be changed to generated UUID?

### ISSUE THREAD

**Issue by aviranco** [dmfay/massive-js#509]
Is the default id field created in db can be changed to create ids of type UUID instead of INTEGER?

**Comment by dmfay** [comment]
You mean for document tables? That's the only place we're creating ids that I can think of...

It's not directly possible at the moment, although you can certainly pre-create document tables with SQL and change the `id` type to UUID. If you need to do it dynamically, you could `db.createDocumentTable`, `db.query` with DDL to change the type, then `db.reload`. @jaimesangcap was looking at more friendly configuration including setting UUID primary keys in #501.
