### ISSUE TITLE
Update massive v2 to use deasync version 0.1.12

### ISSUE THREAD

**Issue by clarenceh** [dmfay/massive-js#518]
Currently, in v2 branch, the package-lock.json file, it's using deasync version 0.1.10. However, there is a bug which cause my existing code failed with the following error:
```
{"name":"mek-api","hostname":"ClarencedeiMac.local","pid":21454,"level":30,"msg":"Current environment: dev","time":"2017-12-26T08:52:26.014Z","v":0}
/Users/clarence/workspace/mek/mek-api/node_modules/deasync/index.js:71
		process._tickDomainCallback();
		        ^

TypeError: process._tickDomainCallback is not a function
```

The error was fixed in deasync 0.1.12. So need to run npm again to update package-lock.json in order to use the newer version of deasync.

Many thx in advance
Clarence

**Comment by dmfay** [comment]
Published as 2.7.3 (`npm i massive@legacy` or `npm i massive@2`), thanks for catching this!
