### ISSUE TITLE
Decomposed results are not ordered correctly

### ISSUE THREAD

**Issue by nireno** [dmfay/massive-js#530]
massive version:  4.6.3

What I did: I ran a raw query with an "order by date DESC" clause.
```javascript
//simplified example
const events = await db.query(`
  select evt_id, evt_occurred_at
  from events
  order by evt_occurred_at desc`, [], {
    decompose: {
      pk: 'evt_id',
      columns: ['evt_id', 'evt_occurred_at']
  })
```

What I expected: The decomposed results should have been ordered in descending order by evt_occurred_at.
What actually happened: The decomposed results were ordered in ascending order by evt_id.

**Comment by dmfay** [comment]
Looks good, I've released 4.6.4. Thanks!
