### ISSUE TITLE
Ability to add comments to fields easily

### ISSUE THREAD

**Issue by flux627** [dmfay/massive-js#534]
Something I never liked about native Postgres SQL migrations was the decoupling between adding columns and their comments. It would be nice to do something like this:

```
exports.up = (pgm) => {
  pgm.createTable( "my_table", {
    id: {
      type: "uuid",
      primaryKey: true,
    },
    created_at: {
      type: "timestamp",
      notNull: true,
      default: new PgLiteral("current_timestamp"),
      comment: "Time this entry was created."
    },
    username: {
      type: "string"
      unique: true,
      comment: "Unique identifier for user."
    }
  })
}
```

Which would automatically add the respective `COMMENT ON COLUMN ...` after creating the table.

**Comment by dmfay** [comment]
Massive isn't a migration framework and doesn't create tables (other than well-defined document tables... which could probably use column comments, to be fair). Did you mean to file this against node-pg-migrate?

**Comment by flux627** [comment]
Yes, I did. Sorry, had both tabs open!
