### ISSUE TITLE
db.table.Save() - Inserting array with composite primary key fails (but used to work)

### ISSUE THREAD

**Issue by gpierrick** [dmfay/massive-js#536]
Table
userId
conversationId
read
deleted

This works
```
return postgres.db.participants.insert(data).then((res) => {
                return resolve(res);
            }).catch((err) => {
                logger.error(err);
                return reject(err);
            });
```

This doesn't
```
return postgres.db.participants.save(data).then((res) => {
                return resolve(res);
            }).catch((err) => {
                logger.error(err);
                return reject(err);
            });
```

It used to work in a previous version (I have one API running the old version of massivejs)

Error message
`Must provide an object with all fields being modified and the primary key if updating`

**Comment by dmfay** [comment]
I notice you're inserting `data[0]` but saving `data` -- is that correct? Can you provide sample data?

**Comment by gpierrick** [comment]
Oops sorry it's meant to be data - also I have just tried insert and that works save doesn't

**Comment by dmfay** [comment]
The error message you received is consistent with passing an array or thing-other-than-an-object to `save`, and that check goes back past 3.1.0. Please provide sample data which triggers the error on save.

**Comment by gpierrick** [comment]
I am still using 2.7.2 on my other project that's probably why.

**Comment by dmfay** [comment]
You can only `save` one object at a time -- it doesn't handle arrays.
