### ISSUE TITLE
duplicate tables when partition of tables exist

### ISSUE THREAD

**Issue by kesavkolla** [dmfay/massive-js#539]
I have partition table using inheritance in PostgreSQL.  For those tables the tables query is retrieving them twice one with parent null and other with parent populated.  This is making the massive to fail with duplicate error while attaching the primarykey

**Comment by dmfay** [comment]
From what I know of partitioning tables, the child tables still have to be named independently so I'm not quite following what's happening here. Can you provide a script with `CREATE TABLE` statements I can use to replicate the issue?

**Comment by dmfay** [comment]
I couldn't run this script as-is. Here's what I got working:

```
create table reservation (
	property uuid not null default uuid_generate_v1mc(),
	reservationid text not null,
	confnum text,
	creationdt timestamp with time zone,
	updatedt timestamp with time zone,
	status text,
	arrivaldt date,
	departuredt date,
	constraint reservation_pkey
		primary key (property, reservationid)
);

create table reservation_hhh (
	property uuid not null default uuid_generate_v1mc(),
	reservationid text not null,
	confnum text,
	creationdt timestamp with time zone,
	updatedt timestamp with time zone,
	status text,
	arrivaldt date,
	departuredt date
) inherits (reservation);
```
I should note the parent `reservation` and child `reservation_hhh` is consistent with how I've used table inheritance previously: two tables, two names, no collision. Massive 4.6.4 loads the database I ran my version of the script against just fine. Is this missing some other piece -- views, functions, scripts?

**Comment by kesavkolla** [comment]
I took the tables.sql that it gets generated and ran in my database here is the output I get

![image](https://user-images.githubusercontent.com/274645/36189286-66ac0a46-1106-11e8-9bae-f26726127a11.png)

**Comment by dmfay** [comment]
ah, found it. I learned more about table inheritance today.

**Comment by dmfay** [comment]
You should be good if you update to v4.6.5.
