### ISSUE TITLE
allowedSchemas is not working for functions

### ISSUE THREAD

**Issue by kesavkolla** [dmfay/massive-js#541]
I've created massive instance like below:

```JavaScript
massive(connectionInfo, {allowedSchemas: ['public', 'integration'], enhancedFunctions: true, excludeMatViews: true});
```

The result had other schemas also with all the available functions in those schemas.

**Comment by dmfay** [comment]
That's an undocumented legacy holdover; functions use [their own whitelist+blacklist](https://dmfay.github.io/massive-js/connecting.html#loader-configuration-and-filtering) and ignore `allowedSchemas`. I'll leave this up to track it but that's going to be a compatibility break that can't entirely be excused as a bug, so it'll be a new major version.

**Comment by dmfay** [comment]
Closing this now that it's tracked.
