### ISSUE TITLE
String like function parameter types don't work if there is a variadic parameter

### ISSUE THREAD

**Issue by mdbiundo** [dmfay/massive-js#544]
Type of variadic doesn't seem to matter.

simple functions to reproduce

```
CREATE OR REPLACE FUNCTION public.teststrings(_str character varying, _txt text, _int integer, VARIADIC _stuff text[])
  RETURNS character varying AS $$
BEGIN
 RETURN _str;
END;
$$
LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.testintegers(_str character varying, _txt text, _int integer, VARIADIC _stuff integer[])
  RETURNS character varying AS $$
BEGIN
 RETURN _str;
END;
$$
LANGUAGE plpgsql;
```
console:

> db > db.public.teststrings('hello world', 'some text', 1, ['foo', 'bar']);
> error: function public.teststrings(unknown, unknown, integer, text[]) does not exist
>     at Connection.parseE (/home/mark/massive-js/node_modules/pg/lib/connection.js:545:11)
>     at Connection.parseMessage (/home/mark/massive-js/node_modules/pg/lib/connection.js:370:19)
>     at Socket.<anonymous> (/home/mark/massive-js/node_modules/pg/lib/connection.js:113:22)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12)
>     at readableAddChunk (_stream_readable.js:250:11)
>     at Socket.Readable.push (_stream_readable.js:208:10)
>     at TCP.onread (net.js:594:20)

> db > db.public.testintegers('hello world', 'some text', 1, [1, 2]);
> error: function public.testintegers(unknown, unknown, integer, integer[]) does not exist
>     at Connection.parseE (/home/mark/massive-js/node_modules/pg/lib/connection.js:545:11)
>     at Connection.parseMessage (/home/mark/massive-js/node_modules/pg/lib/connection.js:370:19)
>     at Socket.<anonymous> (/home/mark/massive-js/node_modules/pg/lib/connection.js:113:22)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12)
>     at readableAddChunk (_stream_readable.js:250:11)
>     at Socket.Readable.push (_stream_readable.js:208:10)
>     at TCP.onread (net.js:594:20)

Let me know if I can add anything.

**Comment by dmfay** [comment]
The variadic argument is an array _inside_ the function body; outside, it's just more arguments and shouldn't be enclosed in a JavaScript array. Invoke your function like this:

```
db.teststrings('one', 'two', 3, 'four', 'five').then(res => {...});
```

**Comment by mdbiundo** [comment]
Ah, ok I hadn't come upon a need to pass a dynamic number of arguments in this way before, so I didn't think to try it! Thanks for the guidance.

In case someone else runs into this issue and comes across this post, the following worked for me:

```
var arr = ['four', 'five'];
db.teststrings.apply(this, _.concat('one', 'two', 3, arr));
```
