### ISSUE TITLE
v5 compatibility breaks

### ISSUE THREAD

**Issue by dmfay** [dmfay/massive-js#546]
Most of these are long-standing TODOs generated as I've been looking at making the API simpler and more consistent. None are happening just yet; this is strictly to keep them visible and track them in one place.

- [x] function loader should use `allowedSchemas` (and possibly more streamlining around the general loader whitelist/blacklist functionality) (#541)
- [x] remove `db.run` (use `db.query`)
- [x] remove Select `options.columns` in favor of `options.fields` (safe) & `options.exprs` (unsafe)
- [x] remove `*` criteria (use `{}`)
- [x] remove direct `order` string interpolation, replace with unsafe `expr` (eg `{order: [{expr: 'a + b', direction: 'desc'}]}`)
- [x] deep insert must be explicitly enabled
- [x] load tables without primary keys
- [x] separate unary and bulk updates
- [x] more info fields on document tables pulled into body on read (created_at, updated_at)
- [x] `updateDoc` (originally `modify`) should take query options object

**Comment by vitaly-t** [comment]
If you take you time, [pg-promise 8.x](https://github.com/vitaly-t/pg-promise/milestone/9) will be released, which will also have a number of breaking changes, although none of those will affect your code :wink:

**Comment by vitaly-t** [comment]
Well, I'm all done with 8.x, in fact did 2 updates since :smile:

**Comment by dmfay** [comment]
@Zolmeister suggests turning deep insert off by default. Given I've seen more issues come up from that feature than anything else in recent memory I'm at least going to think about it -- comment welcome!

**Comment by Zolmeister** [comment]
proposal: deprecate `update({where}, {to}, {options})` in favor of new method `updateAll({where}, {to}, {options})` due to the possibility of field conflicts between `{to}` and `{options}`

**Comment by dmfay** [comment]
I dropped a release candidate last night: `npm i massive@next`. It should be pretty stable from here; there are one or two more things I have in mind but I don't intend any more major disruptions.

Documentation in the package or the `v5` branch is up to date. If you check out the branch and navigate to the docs/ directory, you can run your own instance of the documentation site with `bundle exec jekyll serve` (requires Ruby). I'll be updating the gh-pages branch once this makes it to `master`.

**Comment by dmfay** [comment]
all done!
