### ISSUE TITLE
Is GROUP BY supported?

### ISSUE THREAD

**Issue by brandonmp** [dmfay/massive-js#548]
I'd like to execute a query using `where` and `group by`. I know `where` has pretty robust support, but I couldn't find `group by` referenced in the docs.

Is it possible using the `massivejs` API (besides raw sql in `db.query()`, i mean)?

**Comment by dmfay** [comment]
There's no support for it at present; it's very much in the "nice to have eventually" category.

Depending on what you're trying to do, I'd recommend a view or query file over inlining SQL with `db.query`. The latter is convenient for experimentation but isolating query logic makes it much easier to test completely.
