### ISSUE TITLE
Disable junctions for insert

### ISSUE THREAD

**Issue by samjeffress** [dmfay/massive-js#550]
Hi, 
My objects that I'm storing have both standard postgres columns, and jsonb for storing an original request object. 
I've renamed some columns in my tables to use snake case, and now I have columns that match a nested property name in my object. I'm now getting errors `this.records[0][j].map is not a function` which is from lib/statement/insert.js -> format function. (it's resolving to string values, which aren't mappable)
If I could disable junctions then this wouldn't be an issue - is this available?
Thanks
Sam

**Comment by dmfay** [comment]
It is not, but adding an `ignoreJunctions` option for inserts would be pretty straightforward if you'd like to submit a pull request.

**Comment by samjeffress** [comment]
Added a pr - https://github.com/dmfay/massive-js/pull/551. I went with `deepInsert` as the option name because that's talked about in doco rather than the junctions

**Comment by dmfay** [comment]
Released as 4.7.0, thanks!

**Comment by samjeffress** [comment]
Pleasure :) thanks for your quick feedback 👍

**Comment by tylercollier** [comment]
Is there a way to set global config options for massivejs (I looked all through the doc, which is well written and organized, and didn't see it)? I'd like to default `{ deepInsert: false }` everywhere.

**Comment by dmfay** [comment]
There are global options but that is not one of them. I've been [thinking about changing how that's enabled somehow](https://github.com/dmfay/massive-js/issues/546) for v5, but I've also been pretty busy. I've just thrown a v5 branch up if you or anyone else wants to make a pull request against it.
