### ISSUE TITLE
Batch insert function not returning and no error

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#553]
I am passing in an array of 50K into the insert function, and I am not seeing it return.  Is there a limit to the size of the array to pass the insert function when doing batch inserts?

**Comment by jnystrom** [comment]
Looks I am hitting a limit on the number of values that can be added to a single insert.  Looks like i will have to find a different way to batch load data.

**Comment by dmfay** [comment]
Yeah, Massive doesn't impose any limit -- it's either Postgres or your RAM. Out of curiosity, what are you trying to do with a batch insert of 50k records at a time?!

**Comment by jnystrom** [comment]
I am processing a file of data.

**Comment by dmfay** [comment]
Depending on how much processing you need to do, I'd look into streaming records in and collecting smaller batches to fire at PG, or just using `COPY`.

**Comment by jnystrom** [comment]
I shrunk down to a batch of 2500, and it worked for the insert.  Can I pass through massive to use `COPY`?

**Comment by jnystrom** [comment]
cool, I will try that...thank you!!!

**Comment by vitaly-t** [comment]
@jnystrom If the inserts you are doing do not require much JSON processing that's supported by Massive, then you can do it on a lower level, through its [pg-promise] driver. See [Multi-row insert with pg-promise](https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise).

[pg-promise]:https://github.com/vitaly-t/pg-promise

**Comment by dmfay** [comment]
I assume you got whatever this was working :)
