### ISSUE TITLE
Broken links in doc

### ISSUE THREAD

**Issue by vibl** [dmfay/massive-js#555]
In https://dmfay.github.io/massive-js/connecting.html (and possibly elsewhere), internal links are broken 

For example:
https://dmfay.github.io/queries
https://dmfay.github.io/persistence
https://dmfay.github.io/functions

By the way, it'd be great if users could contribute to the documentation more easily (using GitBook for example).

**Comment by dmfay** [comment]
That's that fixed, thanks for reporting it!

Tell me more about GitBook? What's it got that would make you more likely to contribute to docs there than opening a pull request here?

**Comment by vibl** [comment]
Thanks!

And thank you for Massive, which looks impressive (just starting with it).

About GitBook, I've just realized it wouldn't make much of a difference. I thought it allowed public editing, but in reality only collaborators can edit pages.

It might still be a good option for other reasons (full text search, many plugins dedicated to documentation, coded in JS...), but I imagine you have better things to do :-)

**Comment by dmfay** [comment]
Yeah, I was looking at it and thinking WYSIWYG might be nice for some people but it's all Markdown in the end and the toolchain I've got is nice and simple already. Search is a good point but I don't think Massive's at the level of complexity where we really need that, and I hope to keep it that way! :grin:
