### ISSUE TITLE
"this.records[0][j].map is not a function" when table column missing (caused by deepInsert)

### ISSUE THREAD

**Issue by Zolmeister** [dmfay/massive-js#556]
e.g. table `user` columns `{id: 'text'}`

```
// note throw instead of promise rejection
try {
  db.user.insert({username: 'xxx'})
} catch (err) {
// this.records[0][j].map is not a function
}
```

```
// works
db.user.insert({username: 'xxx'}, {deepInsert: false})
```

**Comment by dmfay** [comment]
Your table only has an `id` column but you're inserting a record with a `username` field? Am I understanding this correctly?

**Comment by Zolmeister** [comment]
Yes

**Comment by dmfay** [comment]
Well, that explains the what, but not the why: why are you inserting a record with a field that doesn't exist in the table? Do you have something set up with rules or triggers?

**Comment by Zolmeister** [comment]
It was a mistake (the testing environment table was wrong), but debugging it was painful because of the opaque error

**Comment by dmfay** [comment]
That makes more sense, thanks. Yeah, the error messaging around it needs some work.
