### ISSUE TITLE
Subqueries

### ISSUE THREAD

**Issue by mike-engel** [dmfay/massive-js#559]
Hey again! I'm wondering if it's possible to include subqueries for a field, at least during `insert`, `save`, `saveDoc`, etc? I tried to find something in the docs, but I couldn't see anything. I'm thinking something like so:

desired SQL:
```sql
INSERT into ACCOUNTS (id, name, item_id) VALUES(DEFAULT, "test", (select * from accounts where name = 'test')
```

desired `insert` (or something like this, since `db.raw` doesn't exist):
```js
// could be `save` or `saveDoc` idk
db.accounts.insert({
  name: "test",
  item_id: db.raw("(select id from accounts where name = 'test')")
}).then(stuff => console.log(stuff))
```

**Comment by dmfay** [comment]
It's a CTE instead of a subquery if that matters, but there's [deep insert](https://dmfay.github.io/massive-js/persistence.html#deep-insert). Nothing for update as yet though, you'd have to do that with a script or function.

**Comment by mike-engel** [comment]
Thanks! Sorry for the grammar mixup. The case I have right now, at least, is probably more complicated but could be broken down. To start, I have two sets of relational data to insert, `accounts` and `transactions`. Accounts is an array, so that's already a bulk add, which doesn't work with deep insert (yet?). Then the transactions need to be added/upserted in bulk, but I only have the account name, not the primary key to those accounts. This is a pretty complex case, but having the ability to do inline CTEs like above would be nice, if a nice API could be designed for it. I can, of course, do this as a raw query, but that's no fun 😉

**Comment by dmfay** [comment]
oh I didn't mean like that -- what you have is a subquery (using a `SELECT` inside another statement), deep insert uses CTEs (`WITH (...) AS x ...`). And yes, it only works with single records because all the child records get the parent record's primary key so you can only do one per query. You could `map` individual accounts with their associated transactions through it if you wanted to avoid writing it out yourself, but if you want to get it all done with one operation I'm afraid you're going to have to write some SQL.

`db.raw` is an interesting thought, but I'm a little nervous about adding more ways to potentially SQL inject yourself in the foot.

**Comment by mike-engel** [comment]
No worries! And I totally understand the part about limiting vulnerable entry points. Like I said, my use case is pretty complicated. What I ended up having to do is something like so which is horribly underperformant, but I'm prototyping and am lazy 😛 

```js
const accountsByPlaidId = groupBy(prop("plaidId"), newAccounts);
const formatTransactions: (
  transactions: ReadonlyArray<PlaidTransaction>
) => any = pipe(
  map((transaction: PlaidTransaction) => ({
    ...transaction,
    plaid_id: transaction.transaction_id,
    item_id: item.id,
    account_id: (accountsByPlaidId[transaction.account_id][0] as Account)
      .id
  })),
  map(
    pick([
      "plaid_id",
      "amount",
      "category",
      "date",
      "location",
      "payment_meta",
      "name",
      "pending",
      "transaction_type",
      "account_id",
      "item_id"
    ])
  )
);

const upsertTransactions = formatTransactions(
  transactions as ReadonlyArray<PlaidTransaction>
);

await Promise.all(
  upsertTransactions.map((t: any) =>
    db.query(
      `
    insert into
      transactions
      (id, plaid_id, amount, category, date, location, payment_meta, name, pending, transaction_type, account_id, item_id)
      values
      (DEFAULT, $\{plaid_id\}, $\{amount\}, $\{category\}, $\{date\}, $\{location\}, $\{payment_meta\}, $\{name\}, $\{pending\}, $\{transaction_type\}, $\{account_id\}, $\{item_id\})
    on conflict (plaid_id) do update set
      amount = excluded.amount,
      category = excluded.category,
      date = excluded.date,
      location = excluded.location,
      payment_meta = excluded.payment_meta,
      name = excluded.name,
      pending = excluded.pending,
      transaction_type = excluded.transaction_type
    `,
      t
    )
  )
);
```

**Comment by vitaly-t** [comment]
@mike-engel such an upsert would be quite inefficient, performance-wise. You'd want to do just a single multi-row insert here. For example see [Multi-row insert with pg-promise
](https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise).

**Comment by mike-engel** [comment]
@vitaly-t I knew that it was incredibly inefficient, but the way I was planning to fix that was much more verbose. Your solution is great, thanks for providing that! It might be useful to have that in the curated docs somewhere (couldn't find it) rather than just the JSDocs
