### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mjacobson7** [dmfay/massive-js#568]
I am using the Decompose feature to help define a nested schema. The purpose of my code is to find a user and return that user along with their supervisor (if they have one assigned to them). 

The problem, is if the user doesn't have a supervisor, the `LEFT JOIN` of the supervisor table will cause null or undefined values to pass through and the decompose feature attempts to build an object out of it. This results in an error:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at transform (/node_modules/massive/lib/util/decompose.js:103:21)
    at module.exports (/node_modules/massive/lib/util/decompose.js:127:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
``` 

Here is the decompose code:
```
dbInstance.user_login([username, companyId],
  {
    decompose: {
      pk: 'id',
      columns: { id: 'id', username: 'username', supervisor_id: 'supervisorId' },
      supervisor: {
        pk: 'id',
        columns: {id: 'id', username: 'username'}
      }
    }
  })
```

Here is my SQL query:
```
SELECT * FROM users u 
LEFT JOIN users supervisor on supervisor.id = u.supervisor_id 
WHERE u.username = $1 AND u.company_id = $2;
```

If I change the `LEFT JOIN` with a `JOIN` I don't get any errors, but I don't get the user object returned to my front end.  

Any help is greatly appreciated!

**Comment by dmfay** [comment]
`SELECT *` from a self-join will return duplicate columns: you'll get an `id` for the user and an `id` for the supervisor, and so on. Massive has no way to tell which is which. Use aliasing to ensure your column names are unique, and update your decomposition schema accordingly. That ought to work better.

**Comment by mjacobson7** [comment]
Thank-you for the quick response.  However, the issue only happens when the supervisor is null.  If I am doing a GET request for a user who has a supervisor, I get the nested object back exactly as expected. 

The issue occurs when the user does not have a supervisor, so the `LEFT JOIN` is joining the user with the supervisor columns which are `NULL`.

**Comment by dmfay** [comment]
I'm honestly surprised it seems to be working that well with that `SELECT` statement. The field consolidation happens in the driver -- while the `SELECT` itself returns multiple `id` columns as appropriate, the results Massive gets back are condensed into objects with keys mapped to column names. If you check the results array returned from the query _without_ decomposition, you should see objects containing one id, one username, etc since duplicate keys overwrite the original.

In fact, what's causing the issue is probably exactly this: your `LEFT JOIN` returns duplicate fields nulled out, which the driver condenses into a "user" `{id: null, username: null}`, which causes problems for decompose trying to apply the schema.

**Comment by mjacobson7** [comment]
That makes sense.  Now how would you recommend I get users that have a supervisor as well as those that don't?  Would it be easier to just do two separate queries; one for the user, then one to get their supervisor if it exists?

**Comment by dmfay** [comment]
No, you can totally still do it in one query! Just alias your columns: 

```
SELECT u.id, u.username, s.id AS supervisor_id, s.username AS supervisor_username
FROM users u
LEFT OUTER JOIN users s ON s.id = u.supervisor_id
```

Then define your `columns` appropriately in your decomposition schema. The nested `supervisor`'s `pk` is `supervisor_id`, and its columns include both `supervisor_id` and `supervisor_username`.

**Comment by mjacobson7** [comment]
Appreciate it! It does look like it's working.  I may end up making separate requests because renaming the properties for the supervisor fields will cause some other issues in my particular application, but I'm glad I was able to get your help. 

Thanks again!

**Comment by dmfay** [comment]
You can de-alias them in the schema:

```
{
  pk: 'id',
  columns: { id: 'id', username: 'username' },
  supervisor: {
    pk: 'supervisor_id',
    columns: {supervisor_id: 'id', supervisor_username: 'username'}
  }
}
```
