### ISSUE TITLE
Dynamic table name in a .sql file?

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#574]
I dont think this is possible, but wanted to make sure.  Can I pass in a dynamic table name as a var ($1) and use that in a .sql file (`select * from $1 where test = $2`) ?

**Comment by dmfay** [comment]
[You can!](https://github.com/vitaly-t/pg-promise/#sql-names)

**Comment by jnystrom** [comment]
Can I use that syntax in a massive .sql file?
