### ISSUE TITLE
Error record.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by eduardomourar** [dmfay/massive-js#579]
In massivejs v4.7.1, I am getting this error when criteria parameter passed does have function `hasOwnProperty()`:
```
TypeError: record.hasOwnProperty is not a function
    at criteria.pk.reduce (data-service\node_modules\massive\lib\table.js:47:16)
    at Array.reduce (<anonymous>)
    at Table.getPkCriteria (data-service\node_modules\massive\lib\table.js:46:28)
    at Table.saveDoc (data-service\node_modules\massive\lib\table.js:177:25)
    at DataTable.save (data-service\data-table.js:79:39)
    at DataService.save (data-service\index.js:144:40)
    at UserDirectory.save (iam-service\user-directory.js:68:36)
    at <anonymous>
```

I have created on [my repo branch](https://github.com/eduardomourar/massive-js/tree/fix-has-own-property-issue) this test that fails:
```
it('passing object without hasOwnProperty method', function () {
  const criteria = Object.create(null);
  criteria.title = 'Document 1';
  return db.docs.findDoc(criteria).then(docs => {
	assert.lengthOf(docs, 1);
	assert.equal(docs[0].id, 1);
	assert.equal(docs[0].title, 'Document 1');
	assert.equal(docs[0].description, 'lorem ipsum etc');
  });
});
``` 

One possible solution is to replace every time hasOwnProperty is used with `Object.prototype.hasOwnProperty.call(obj, property)`.
I will submit a PR with code and test if that makes sense.

**Comment by dmfay** [comment]
Can you explain how this came up? Your workaround seems fine if there's a common or compelling reason criteria and options objects might not have standard prototype methods but I'd like to know _why_ this could happen first.

**Comment by vitaly-t** [comment]
Once upon a time I ran into the same issue within pg-promise: https://github.com/vitaly-t/pg-promise/pull/290

**Comment by dmfay** [comment]
oh, it's GraphQL. @eduardomourar feel free -- I'm traveling the next few days but I should be able to review and release.

**Comment by eduardomourar** [comment]
@dmfay and @vitaly-t, thanks. In our particular case, the [parse method](https://nodejs.org/docs/latest-v8.x/api/querystring.html#querystring_querystring_parse_str_sep_eq_options) from nodejs querystring was causing the issue. The note there states: 

> Note: The object returned by the querystring.parse() method does not prototypically inherit from the JavaScript Object. This means that typical Object methods such as obj.toString(), obj.hasOwnProperty(), and others are not defined and will not work.

I will change massivejs v2 and v4 code and submit PR soon.
