### ISSUE TITLE
sql file with multiple commands

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#586]
I have created a sql file that has multiple insert statements within it.  I did this before reading that you should only have 1 command per file.  The inserts seem to all work, but sometimes it seems like there is a hang running the file.  WOuld the sql be more reliable if I did move the sql inserts into different sql files?

**Comment by dmfay** [comment]
Probably. The wording in the docs is a bit strong (the tests run on schemas generated with multi-statement files) but for production usage you want to avoid One Big Transaction like the plague. If I had to guess, you're probably running into a lock partway through.
