### ISSUE TITLE
Massive in a separate file

### ISSUE THREAD

**Issue by Extarys** [dmfay/massive-js#590]
It seems that I cannot make Massive works on a separate file:

I would like to include a db file in all the needed routes like:
```
const db = require('./db')
db.mytable.count()
```
How can I do that? It return a promise or just throw some errors related to async.

**Comment by dmfay** [comment]
Your `db` module will need to wrap the process of connecting to Postgres and export a function which returns the connected instance. Then when you `require` it, you'll have to `await` or otherwise resolve that function to get the instance out.
