### ISSUE TITLE
FindOne does an explicit order by?

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#593]
Hey, I added monitoring to my massive connection, and noticed on a simple `findOne` there is an explicit `order by <PK>`  added to the sql generated by Massive and does not seem to use a limit.  Is there anyway to not have the order by added?

call:  `await db[tableName].findOne({journal_id : <GUID>});`

sql:  `SELECT * FROM "<tableName>" WHERE "journal_id" = <GUID> ORDER BY "id"` (this is what I saw output after adding pg-monitor and attaching to the massive db connection.

UPDATE:

I just tried to use `find` with `limit:1` as an option, but the `ORDER BY id` is still in the sql.

**Comment by dmfay** [comment]
Pass `{order: null}` in your options to disable it entirely.

**Comment by jnystrom** [comment]
@dmfay thanks.  I am still confused as to why the `findOne` is sending a query that is not limiting the results to 1?

**Comment by dmfay** [comment]
Inertia -- the original implementation deferred to `find` and just picked the first result off of that. Nobody's noticed until now. Feel free to drop a pull request!
