### ISSUE TITLE
Feature: iterator/generator based output as alternative to streams

### ISSUE THREAD

**Issue by rijnhard** [dmfay/massive-js#613]
Streams are a nice interface to handling larger amounts of query data. but streams are fairly verbose to implement, especially if you do the error handling and backpressure properly. 

Generators are a much more familiar interface, and much simpler in the use case

e.g. using async iterators (which aren't standard yet)

```javascript
async function processQueued() {
    const iterator = b.tests.find({priority: 'low'}, {iterator: true});

    for await (const item of iterator) {
        await doRandomProcess(item);
    }
}
```

This is much simpler then handling streams, the only real drawback is that async generators are not standard yet, but if resolving a promise with an iterator is sufficient then this isn't an issue.

**Comment by vitaly-t** [comment]
The syntax shown in the example requires Node.js v9.2+

**Comment by rijnhard** [comment]
Not saying it should be done immediately, but it is a nice usability
enhancement for the future

**Comment by dmfay** [comment]
It would be cool! I'm going to punt on it though -- most of the work to be done here would fit in better at the driver level so there's a single consistent implementation whether you're using Massive or not. So if you're interested in working toward it I'd suggest pulling [pg-promise](https://github.com/vitaly-t/pg-promise) (hi Vitaly!) instead.

**Comment by rijnhard** [comment]
Thank you for the feedback @dmfay

@vitaly-t should I open a feature request on pg-promise?

**Comment by vitaly-t** [comment]
@rijnhard I don't know what feature request you could open against `pg-promise`, as it already supports both ES6 generators and ES7 `async/await` in a generic way.

**Comment by rijnhard** [comment]
@vitaly-t I may be missing the boat, so excuse me if this is a dumb statement. But I had a look at pg-promise and how it handles generators and thats mainly in the `transaction`/`task` area, I'm talking about having an alternative to the `stream` API, because it has the same use case as the stream API, in that it allows you to handle large datasets with backpressure just like streams. The only real difference is that it's a much nicer API to work with, where streams get clunky and error-prone quickly.

**Comment by vitaly-t** [comment]
> in that it allows you to handle large datasets with backpressure just like streams

For that `pg-promise` supports sequences, see method [sequence](http://vitaly-t.github.io/pg-promise/Task.html#sequence).

**Comment by rijnhard** [comment]
@vitaly-t, @dmfay this may be asking for a bit much, but I'm struggling to figure out how to use sequences in say this example [massive-js#search](https://dmfay.github.io/massive-js/queries.html#search), could you give me an example?

**Comment by vitaly-t** [comment]
@rijnhard I don't see any asynchronous sequence there, it's just one asynchronous request, which gives you all the data at once, so you don't need to sequence it, you can just loop through it synchronously.

**Comment by rijnhard** [comment]
TBH at this rate I think it's probably just going to be easier if I map the stream to a generator on my own, kind of how [es6-stream](https://www.npmjs.com/package/es6-stream) does it (but in a nicer way) and maybe find a way to upstream that with a similar structure to [node-pg-query-stream](https://github.com/brianc/node-pg-query-stream).

**Comment by dmfay** [comment]
Afraid I haven't gotten into pgp's sequences much at all, so I can't really help you there. If it makes it in upstream though it shouldn't be too much work to add proper support for it through Massive though!

**Comment by rijnhard** [comment]
So for completeness and anyone else looking to make this work:

I decided stuff it and forked [node-pg-query-stream](https://github.com/brianc/node-pg-query-stream) into [node-pg-query-iterator](https://github.com/rijnhard/node-pg-query-iterator) and got about 70% of the way with it (with some babel issues) and then came across [this gem](https://jakearchibald.com/2017/async-iterators-and-generators/) and tweaked it into this:

```javascript
/**
 * Converts a stream to an async iterator
 * @template T
 * @param {ReadableStream<T>} stream
 * @return {Promise<AsyncIterable<T>|Error>}
 * @see https://jakearchibald.com/2017/async-iterators-and-generators/
 * @todo figure out how it handles stream error events?
 */
export async function* streamToIterator(stream) {
    // Get a lock on the stream
    const reader = stream.getReader();

    try {
        // initial read so that we can error handle better
        let { done, value } = await reader.read();

        while (!done) {
            yield value; // chunk

            // Read from the stream
            ({ done, value } = await reader.read());
        }
        reader.releaseLock();
    } catch (e) {
        reader.releaseLock();
        // on an error the iterator does stop.
        throw e;
    }
}
```

But then found this [stream_readable_symbol_asynciterator](https://nodejs.org/dist/latest/docs/api/stream.html#stream_readable_symbol_asynciterator)

So I dont think any of this is needed, just sitback and wait for it to be adopted, and if you cant wait, just use the transformer above (I am using the transformer for now)
