### ISSUE TITLE
db.withTransaction using async/await not rolling back

### ISSUE THREAD

**Issue by devlemire** [dmfay/massive-js#617]
## Summary
From my understanding of the documentation on using `db.withTransaction` it sounded like any time the promise is rejected, all `tx` queries would be rolled back. However, I'm seeing my queries persist when the promise does get rejected. I want to believe it's just a lack of understanding on my part.

### Code demonstrating the behavior
```js
const startChargeTransaction = async function(db, stripe, meta) {
  let stripeCharge

  try {
    // Create a new stripe charge
    stripeCharge = await stripe.charges.create({
      amount: meta.cost,
      currency: 'usd',
      source: meta.token.id,
      description: meta.description
    })

    await db.withTransaction(async tx => {
      // Store the successful charge in our database
      await tx.payments.store_charge({
        stripe_id: stripeCharge.id,
        amount: meta.cost,
        description: meta.description,
        user_id: meta.user_id,
        sf_id: meta.sf_id
      })

      // Update the user's enrollment to reflect a successful payment
      await tx.query(
        `UPDATE enrollments SET ${meta.column_to_update} = TRUE WHERE user_id = ${
          meta.user_id
        } AND session_id = ${meta.class_session_id}`
      )
    })
  } catch (err) {
    console.error('startChargeTransaction failed in payments_controller.js:', err)
    await stripe.refunds.create({ charge: stripeCharge.id })

    throw new Error(
      'startChargeTransaction failed. However, queries were successfully rolled back and the stripe charge was refunded!'
    )
  }
}
```

## Expected behavior
My update query on table `enrollments` purposely fails because a table of `enrollments` does not exist. I would then expect to not see a new record in the `charge` table when running `tx.payments.store_charge`.

## Actual behavior
My `charge` table gets populated with a new record even though the transaction throws a rejection.

## Additional context
The query for `tx.payments.store_charge`:
```sql
INSERT INTO charge (stripe_id, description, amount, status, "createdAt", "updatedAt", user_id, sf_id)
VALUES (
  ${stripe_id},
  ${description},
  ${amount},
  'paid',
  NOW(),
  NOW(),
  ${user_id},
  ${sf_id}
);
```

**Comment by devlemire** [comment]
## More Context

I'm calling this utility function (`startChargeTransaction` ) from a method that gets called when hitting `POST - /api/payments/class_deposit`. The method looks like this:

```js
  pay_class_deposit: async (req, res) => {
    try {
      // Get the db instance from app
      const db = req.app.get('db')
      // Get the stripe instance from app
      const stripe = req.app.get('stripe')
      // Get the user_id of the logged in student
      const { user_id } = req.user
      // Get the required payment information from the request body
      const { token, cost, class_session_id } = req.body
      // Get the most up to date email for the logged in user
      const [{ email }] = await db.get_user({ user_id })
      // Get the user's salesforce id from the enrollments table
      const [{ sf_id }] = await db.get_salesforce_id({
        user_id,
        session_id: class_session_id
      })

      // Format the Stripe charge description
      const description = `Class deposit for ${email}`

      // Call the startChargeTransaction utility function
      await payments_utils.startChargeTransaction(db, stripe, {
        token,
        cost,
        email,
        user_id,
        description,
        column_to_update: 'has_paid_deposit',
        class_session_id,
        sf_id
      })

      res.sendStatus(200)
    } catch (err) {
      console.error('pay_class_deposit method failed in payments_controller.js:', err)
      res.status(500).send(err)
    }
  }
```

**Comment by devlemire** [comment]
## Giphy of it in action

https://giphy.com/gifs/2tTKxmjDpz4B0a3Dkb/fullscreen

**Comment by devlemire** [comment]
P.S I appreciate the quick reply and you looking into this for me. I'm a huge fan of the massive ORM and this is a real road block right now for me!

**Comment by dmfay** [comment]
congrats, you found a bug! Script and function executors were retaining the original instance handle and weren't getting routed through the transaction. Pull down v5.1.1 and you should be all set.

**Comment by devlemire** [comment]
I'm unable to use version 5.1.1, on NPM it also says the latest is still 5.1.0.  Using `yarn add massive@latest` provides me with `5.1.0` and doing `yarn add massive@5.1.1` results in an interactive menu to choose a version with the latest being `5.1.0`.

**Comment by dmfay** [comment]
I forgot I had my npmrc set up to publish to a private registry 🤦‍♀️ It's up on the public one now.

**Comment by devlemire** [comment]
Booyah! Transactions are working like a charm now! Awesome! Thanks for your speedy help, you made my boss very happy 👍
