### ISSUE TITLE
Function script does not exist

### ISSUE THREAD

**Issue by DriscollRichie** [dmfay/massive-js#620]
## Summary
db.listFunctions() provides an array of my function, but massive says function does not exist.

#Example
<img width="1440" alt="screen shot 2018-08-03 at 3 04 17 pm" src="https://user-images.githubusercontent.com/36280478/43665883-e2adfeb6-972e-11e8-8584-605f7d09d4bc.png">

## Expected behavior
The function to exist.

## Actual behavior
The function does not exist.

**Comment by dmfay** [comment]
It says `db.get_bins` is not a function; is there anything there or is it just `undefined`?

Also, you'll need to `await` that invocation but that's a separate issue.

**Comment by vitaly-t** [comment]
@DriscollRichie The error tells you, that what you defined as `get_bins` in file `binsCtrl.js`, is not a function. Looks like an error on your side.

**Comment by DriscollRichie** [comment]
@dmfay It showed it as an available function in the console when I console.logged `db.listFunctions()`, but it turns out that the `await` was the problem. Such a simple mistake. Don't code when you've been drinking! Sorry for the foolishness. Thank you!

**Comment by vitaly-t** [comment]
> Don't code when you've been drinking

Seriously? That is the only way to do it! :smile:

**Comment by dmfay** [comment]
Obviously the solution is to drink more and get on that Ballmer peak :wink:
