### ISSUE TITLE
Using saveDoc() for storing foreign key along with Json data

### ISSUE THREAD

**Issue by nikhilag** [dmfay/massive-js#622]
As per the documentation on the page https://dmfay.github.io/massive-js/documents.html, 

> Document tables may be extended with new columns and foreign keys. 

However, I have not been able to find a way to use the API to store JSON data along with foreign key in an existing table. How can I save data for other columns in a document table?

**Comment by dmfay** [comment]
Document tables are still tables and you can use both the regular table and the document API methods with them. The document body is stored in a column named `body`. For example if you need to add extra fields on creating a new document:

```js
const recordWithBodyAndOtherStuff = await db.extendedDocumentTable.insert({
  some_fk: 123,
  another_field: 'something goes here',
  body: {
    foo: 'bar'
  }
});
```
When you don't need the extended information, you can continue to use the document API:

```js
const justTheBody = await db.extendedDocumentTable.findDoc({foo: 'bar'});
```
