### ISSUE TITLE
[Q] Maybe use pg_attribute to get columns while loading relations and views?

### ISSUE THREAD

**Issue by btd** [dmfay/massive-js#628]
This is only because of AWS bug (i see you know about it (https://forums.aws.amazon.com/thread.jspa?messageID=860564&tstart=0))
I did workaround not using information_schema.columns (https://github.com/InGo-LLP/massive-js/commit/38dbd3e5ea538bd7c63c207ae55eeed8f38004de) and using pg_attribute.

Do you consider such PR? 

Thank you

**Comment by btd** [comment]
@dmfay i got a problem because of auto minor version upgrade option. I did not expect such thing to happen at all.

**Comment by btd** [comment]
I created https://github.com/dmfay/massive-js/pull/629 let me know if you are good with it. I understand that it is not adding anything new.

**Comment by dmfay** [comment]
looks great! Pull down 5.2.1 and you should be all set :)

**Comment by btd** [comment]
@dmfay Thank you very much 🎉 🎉 🎉
