### ISSUE TITLE
Better parameter handling for tasks + transactions

### ISSUE THREAD

**Issue by vitaly-t** [dmfay/massive-js#631]
Something to consider, for the tasks + transactions support.

`pg-promise` has a number of methods for tasks and transactions, and this library wraps some of them. But the way it does so is not consistent with how `pg-promise` does it. Each task and transaction method uses a reversed-optional approach, to make the callback function the last parameter, which allows for easier-to-read code. Plus the way typing is supported there is also quite complex. For example, those methods support `number` + `text` as option `tag` passed in directly.

[The logic of correct handling of all parameters supported by tasks and transaction is quite complex](https://github.com/vitaly-t/pg-promise/blob/master/lib/utils/public.js#L553). And this is why it was moved into an utility method [taskArgs], so if you want to create a custom task / transaction method, you should reuse the exact parameter handling, consistent with the existing methods.

i.e. methods such as `withConnection ` and `withTransaction` should make use of method [taskArgs], to support all parameters in the way that's consistent with `pg-promise` existing methods for tasks and transactions - `method([options], cb)`.

Method [taskArgs] has been there for a while, but I didn't see before how you went about implementing those custom methods. And as a result, they do not support the full syntax supported by `pg-promise`. If you refactor your code into using [taskArgs], then everything `pg-promise` supports for tasks and transactions will become supported automatically, and not just what's supported presently, but also what may become supported in the future, as you would correctly wrap all the parameters and pass them on.

And as a result, you won't need to document the complex parameters for those methods, you will be able to just forward it to `pg-promise` documentation of the method used underneath.

---

The approach is quite simple to use...

At the beginning of your custom method you do this:

```js
const args = pgp.utils.taskArgs(arguments); // prepare all arguments
```

Then you do all the processing as needed by your method, and when it is time to forward to the corresponding method, like `task`, for example, you do:

```js
return obj.task.apply(this, args);
```

So you won't care for the complex parameter syntax supported by the method `task` here, while guaranteeing that it is passed on correctly always.

[taskArgs]:http://vitaly-t.github.io/pg-promise/utils.html#.taskArgs

**Comment by vitaly-t** [comment]
@dmfay May I ask why you decided to keep the same `cb, [options]` order in place of the `pg-promise` version of `[options], cb`?

The reason it is this way in `pg-promise` is to make the code much easier to read. You would see it this way once you start passing in options.

Here's a typical example of using tags:

```js
db.tx('my-tx-reference', t => {
 /// implementation
})
```
In your approach you would end up with the tag being at the end of the transaction, which makes awkward to spot right away, especially with a long implementation body.

**Comment by dmfay** [comment]
Yeah it's a bit clunky, but I didn't want to bump the major version over something with this limited scope. I'll reevaluate it later on.
