### ISSUE TITLE
Options fields does not work for insert

### ISSUE THREAD

**Issue by apsavin** [dmfay/massive-js#634]
## Summary
Options fields does not work for insert

### Database setup
```sql
CREATE TABLE things (
  id SERIAL PRIMARY KEY,
  stuff TEXT
);

grant select (id) on things to my_role;
```

### Code demonstrating the behavior
```js
db.things.insert({ id }, { fields: ['id'] });
```

## Expected behavior
Insert should select only specified `id` field

## Actual behavior
Insert selects all fields so the database throws access error

**Comment by apsavin** [comment]
It seems that the same thing with `update` method.

**Comment by dmfay** [comment]
Delete too, all three persistence statements just throw a `RETURNING *` on so `options.fields` and `options.exprs` are basically ignored. It makes sense that you'd want to do that with column security though. If you'd like to take a stab at it feel free, or I'll have time soon enough.

**Comment by apsavin** [comment]
Thanks for the quick response and for massive.js!

I made a workaround on my side for now. Unfortunately, I have no time for the PR at the moment. But I don't think that there's need to hurry. I will come with PR later if you will not fix the issue until then.

**Comment by dmfay** [comment]
Done in 5.4.0 :tada:
