### ISSUE TITLE
How do I add coordinate Document Tables creation with my migration tool?

### ISSUE THREAD

**Issue by vibl** [dmfay/massive-js#635]
I need to add columns to a Document Table. What is the recommended practice to make sure the table has been created (by `db.saveDoc('myTable'...)`) before running the migration script that will add the columns to it?

I use https://github.com/golang-migrate/migrate, a simple CLI tool that uses SQL files for migration. It doesn't have the ability to execute arbitrary scripts has part of a migration plan (yet: https://github.com/mattes/migrate/issues/171).

**Comment by dmfay** [comment]
I usually just copy out the [document table DDL](https://github.com/dmfay/massive-js/blob/master/lib/scripts/document-table.sql) into my migration scripts if I need to customize them. You'll need to replace the tokens in that file: `schema` and `table` should be pretty obvious, `index` can be whatever you like, and `pkType` + `pkDefault` should be either `SERIAL` and nothing, or `UUID` and one of the [UUID generation functions](https://dmfay.github.io/massive-js/documents.html#primary-key-default-data-type).

**Comment by vibl** [comment]
Thanks!

I wrote a script that does the job: https://gist.github.com/vibl/928d5d2b56e9575f250245c3520f6d40

Do you think if would be worth creating a module for it?

**Comment by vibl** [comment]
Thanks! I think it would be useful to include it in the doc.

**Comment by dmfay** [comment]
Migrations are out of scope for Massive, but of course you can publish whatever extensions you like to the registry :) You're right it couldn't hurt to be a little more specific about it in the docs though.
