### ISSUE TITLE
framework example for express.js

### ISSUE THREAD

**Issue by cpainterwakefield** [dmfay/massive-js#643]
Please let me know if there is a different discussion forum I should be posting on...
I'm a newbie to express.js and am trying to figure out the best practice for using massive with it.
The express.js framework example in the docs is not obviously compatible with the project you get from express generator.  To wit, the generator gives you a script, bin/www, which requires app.js and does all of the http and listener stuff.  I've read that the reason for this is for testing purposes.
My impression from the docs is that, if I do it right, I can get a bare Database object (not a promise) stored in my app object.  I've tried all kinds of hacks, and I can't seem to do this.  I always get a promise, which requires lots of ugly extra code when I want to query anything.  Apologies if this is a newbie question, but is there a way around this problem?
A follow on would be, is there a "best practices" example of using massive with express anywhere (I can't find anything for massive > 2.0).

**Comment by pketh** [comment]
the documentation recommends app.set but is really vague on how to use this. I agree that a specific example would be useful

**Comment by pketh** [comment]
update: found one on https://massive-js.readthedocs.io/en/v2/quick_start/ that's helpful

```
var express = require("express");
var app = express();
var http = require('http');
var massive = require("massive");
var connectionString = "postgres://massive:password@localhost/chinook";

// connect to Massive and get the db instance. You can safely use the
// convenience sync method here because its on app load
// you can also use loadSync - it's an alias
var massiveInstance = massive.connectSync({connectionString : connectionString}) 

// Set a reference to the massive instance on Express' app:
app.set('db', massiveInstance);
http.createServer(app).listen(8080);
```

**Comment by cpainterwakefield** [comment]
Yes, the docs you reference above are specifically for version 2, whereas I believe massive is now up to version 5.

**Comment by cpainterwakefield** [comment]
Yes, that was the example that I was talking about in my original post; Express generator provides a separate file, bin/www, that actually runs the webserver.  This is separate from app.js, apparently because you want to be able to run the app without a webserver for unit testing purposes.  (That isn't critical to me at this time, but it might be in the future.)  I can't figure out how to ensure I have a (non-promise) db object by the time the app starts up; you can't put "await" in app.js, for instance.  I was just hoping there was another way that someone could suggest.  Right now all my controller code looks like:

```
module.exports.foos = (req, res) => {
  var db = req.app.get('db');
  db
  .then(db => {
    db.foo.find()
    .then(results => {
      res.json(results) 
    }); 
  });
};
```
which is annoying for the amount of nesting.  I am still new to js and node, though, so probably I will figure out better ways in time.

**Comment by dmfay** [comment]
Look for the `server.listen(port);` call in bin/www. When you connect Massive, `app.set` and call `server.listen` in the `.then()` instead of where it currently is. (If you're feeling like having some fun, you _could_ put it in an [async IIFE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/async_function#Simple_example)).

Your route/controller can be an async function and `await` the `find`. All the Massive documentation uses `.then()` to maximize compatibility, but async/await is much nicer.

**Comment by cpainterwakefield** [comment]
Thank you, that is very helpful!

I'm still a little fuzzy on where I can use async and await in a node app, and the proper way to use them.  Documentation on the web is all over the place!

**Comment by dmfay** [comment]
Any function that returns a promise can be made an async function. Invocations of functions which return promises (async or not) can be awaited but only from inside async functions; the `await` keyword is invalid outside that context. For general documentation, MDN is basically the gold standard.

**Comment by lfurzewaddock** [comment]
@cpainterwakefield - I can thoroughly recommend Kyle Simpson's JS courses on [Frontend Masters](https://frontendmasters.com/) and his series of books: [You Don't Know JS](https://github.com/getify/You-Dont-Know-JS), which are available free on GitHub and published through O'Reilly.
