### ISSUE TITLE
LIKE comparison on array using ANY()

### ISSUE THREAD

**Issue by nkramaric** [dmfay/massive-js#645]
## Summary
I want to query all the elements in an array using the ILIKE operator. In Postgres I would normally do this using:

```
SELECT * FROM persons WHERE ANY(occupations) ilike '%developer%'
```

### Database setup
```
CREATE TABLE persons (
  id SERIAL PRIMARY KEY,
  occupations TEXT[]
);
```

### Code demonstrating the behavior
```
db.persons.find({ 'ANY(occupations) ilike': '%developer%' });
```

## Expected behavior
I expect to receive all the persons with the occupation like developer

## Actual behavior
Received an SQL error. Looks like its attempting to convert the 'any(occupations)' into a column. See here: 

SELECT * FROM "persons" WHERE "ANY(occupations)" ILIKE '%developer%'

Please let me know if there is another way to perform this query.

**Comment by dmfay** [comment]
You'll have to use a script, function, or view that pre-filters occupations; criteria keys can't be arbitrary SQL snippets, since that invites injection attacks.

**Comment by vitaly-t** [comment]
The underlying driver will safely format it, and happily execute:

```js
function getPersons(occupation) {
    const match = '%' + occupation + '%';
    return db.instance.query('SELECT * FROM persons WHERE ANY(occupations) ILIKE $1'', match);
}
```
