### ISSUE TITLE
Transaction that does insert and uses the id from that insert for next insert in transaction

### ISSUE THREAD

**Issue by jnystrom** [dmfay/massive-js#656]
WIthin a transaction, I am trying to insert an array of records, use the ids that were created from that batch insert to insert child records using the created id.  I am getting the error below.

```
TypeError: Cannot read property 'promise' of undefined
message:"Cannot read property 'promise' of undefined"
stack:"TypeError: Cannot read property 'promise' of undefined\n    at Writable.save (/Users/johnnystrom/dev/flock/pimms-ts/node_modules/massive/lib/writable.js:128:37)\n    at SessionService.<anonymous> (/Users/johnnystrom/dev/flock/pimms-ts/lib/services/sessionService.js:60:50)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/johnnystrom/dev/flock/pimms-ts/lib/services/sessionService.js:13:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
__proto__:Error {constructor: , name: "TypeError", message: "", …}
```

Code:

```
db.withTransaction(async (tx: any) => {
            try {
                const savedRecs = await tx.localizations.insert(formattedLocalizations);
                const networkIntegrations = await this.repo.getNetworkIntegrations(sessionId);
               // no db actions done here
                const integrationSubmissions = this.createIntegrationSubmissions(
                    sessionId,
                    savedRecs,
                    networkIntegrations
                );
                await tx.integration_submissions.insert(integrationSubmissions);
                // update session to processedAt
                await tx.sessions.save({ id: sessionId, processed_at: moment().utc() });

                return;
            } catch (error) {
                this.log.error('Error adding recs:', error);
                throw error;
            }
        });
```

The code above: the line that errors is the `  await tx.integration_submissions.insert(integrationSubmissions);`.  That line is the one that is trying to insert w/ id created in the first tx call (` const savedRecs = await tx.localizations.insert(formattedLocalizations);`).If I remove that line it works.

Any advice would be greatly appreciated.

Thanks,.

**Comment by jnystrom** [comment]
One more thing.  I got it to work when I switched the last 2 `tx` calls:

```
 await tx.integration_submissions.insert(integrationSubmissions);
await tx.sessions.save({ id: sessionId, processed_at: moment().utc() });
```

TO:

```
 await tx.sessions.save({ id: sessionId, processed_at: moment().utc() });
await tx.integration_submissions.insert(formattedSubmissions);
```
Does this make any sense????

**Comment by dmfay** [comment]
Did you do something with `db.instance.$config`, most likely as part of setup, or maybe pass `undefined` explicitly as the third argument when instantiating Massive? If you look at the part of the Massive code indicated by the stack trace, that's what it's trying to pull the `promise` property out of. The stack trace also points to `save`, not one of the `insert`s, and if that's accurate your real problem is that `Writable.save` is not getting what it wants. Fixing `db.instance.$config` should make it give you a more useful error message.

**Comment by vitaly-t** [comment]
> Did you do something with db.instance.$config

That property is read-only :wink:

**Comment by jnystrom** [comment]
so I added `undefined` and that seemed to work, but seeing the same error again.  Here is my Massive connect:

```
 MassiveRepository.db = await Massive(
            this.config.databaseUrl,
            {
                allowedSchemas: ['public'],
                functionBlacklist: '%_raster%, postgis%, raster_%, st%, %geometry%, %geography%, pgis%',
            },
            undefined
        );
```

**Comment by jnystrom** [comment]
@vitaly-t, would it make sense that it works sometimes?

**Comment by vitaly-t** [comment]
> @vitaly-t, would it make sense that it works sometimes?

Depending on the business logic, and how it works underneath, perhaps, but it is hard to see how exactly.

**Comment by jnystrom** [comment]
@vitaly-t so, I did more digging in my code, and noticed that I was calling an insert with an empty array, once I did a check there...everything worked.

**Comment by vitaly-t** [comment]
@jnystrom Obviously, since the failing code is conditional on that check - 

https://github.com/dmfay/massive-js/blob/d6a359858484153e3fdd1442c1040a06ef0c277b/lib/writable.js#L76

Makes it a work-around for you, not a fix.

**Comment by jnystrom** [comment]
I added this:

```
  if (integrationSubmissions && integrationSubmissions.length > 0) {
      const formattedSubmissions = humps.decamelizeKeys(integrationSubmissions);
      savedSubmissions = await tx.integration_submissions.insert(formattedSubmissions);
  }
 // update session to processedAt
await tx.sessions.save({ id: sessionId, processed_at: moment().utc() });
```
After adding this, when there is data in the array, it does work.  I agree that it does still seem like there is something in the framework that could be fixed.

**Comment by dmfay** [comment]
I'd even cached the promise implementation on `db` up front, but there were several places it wasn't being used :woman_facepalming:

Update to 5.7.1 and you should start seeing more informative error messages in transactions/tasks.

**Comment by vitaly-t** [comment]
@dmfay places missed:

https://github.com/dmfay/massive-js/blob/a429162c08b9c08a2029f54a43cb9171fa0ed6bd/lib/loader/functions.js#L6

https://github.com/dmfay/massive-js/blob/fd15567acbca628da5152a8c0e20712c86220f49/lib/executable.js#L101

**Comment by dmfay** [comment]
I don't know how I missed the one in `executable`, but loaders don't have access to `db` and shouldn't be getting called in a transaction.... although Postgres _does_ have transactional DDL so maybe it'd work? I'll have to look into that.
