### ISSUE TITLE
Massive.js is not working with auto-increment fields

### ISSUE THREAD

**Issue by andrerpena** [dmfay/massive-js#659]
Hi. Thanks for this fantastic tool.

I'm trying to run a very simple example: 

```
massive({
  host: '127.0.0.1',
  port: 5432,
  database: 'crm',
  user: 'hyperforms',
  password: 'hyperforms'
}).then((db: any) => {
  db.contact.save({
    full_name: 'andre pena'
  }).then((andre: any) => {
    console.log(andre)
    process.exit(0)
  }).catch((ex: any) => {
    console.log(ex)
    process.exit(1)
  })
})

```

This is my `contact` table:

```
create table contact
(
  id   serial not null
    constraint contact_pk
      primary key,
  text integer
);

```

`db.contact` has an `id` column which is an auto-increment primary key. This is what is happening:

- If I specify the `id`: It works
- If I don't specify the `id`: Save returns an empty array `[]`, with no errors but nothing is inserted.
- If I specify a null or undefined `id`: It fails with these details: `Failing row contains (null, null).`

The problem is, of course, that I can't specify an auto-increment column. Any idea on how to fix this?

Thank you very much.

**Comment by dmfay** [comment]
Autoincrements are fine; your problem is in your `CREATE TABLE` definition :) You've got a column named `text` instead of `full_name` (and it's an int, for good measure). The `full_name` in your `save()` call it isn't a valid column, so you effectively have a no-op instead of the insert you want.

**Comment by vitaly-t** [comment]
@andrerpena  And in case you do have to use `text` as column name, it needs to be in double-quotes: `"text"` :wink:

**Comment by charmander** [comment]
@vitaly-t No, it doesn’t.

**Comment by andrerpena** [comment]
@dmfay I cannot believe I didn't see this 🤪Thank you and sorry.

@vitaly-t Thanks but I just made some tests and apparently reserved words, like `null` require you to use double quotes. However, column types are not considered reserved words. You can call a column `text` or `varchar`, for example, without the quotes.
