### ISSUE TITLE
Incompatibility with pg-promise event receive (with camel casing)

### ISSUE THREAD

**Issue by johnbiundo** [dmfay/massive-js#665]
## Summary
Attempting to supply pg-promise driver config that utilizes the receive event to camelCase column results, per https://github.com/vitaly-t/pg-promise/issues/78

I realize this may not be a bug, in that Massive does the database introspection at instantiation, and I guess this camel casing is probably interfering.  I'd be willing to take a stab at implementing a feature that would allow this configuration in a PR if I could get some guidance.  I'm a big fan of Massive, and live more in userland than in contributing to OS projects, but I'm game to give it a try.

I realize that camelCasing isn't really do-or-die on the JS side, but I do prefer it if it could be done more-or-less transparently, and this seemed like the best approach to make it work.

### Database setup
```
CREATE TABLE test (
  column_one int
);
```

### Code demonstrating the behavior
```
const massive = require('massive');
const Promise = require('bluebird');
const pgp = require('pg-promise');

require('dotenv').config();

const massiveConnSettings = {
  port: 5432,
  ssl: false,
  poolsize: 10,
  user: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  host: process.env.DB_HOST,
  database: process.env.DB_NAME,
};

// settings passed through massive to pgp
const driverSettings = {
  promiseLib: Promise,
  receive: (data, result, e) => {
    camelizeColumns(data);
  },
};

// function to camel case database columns.
// reference: http://vitaly-t.github.io/pg-promise/global.html#event:receive
function camelizeColumns(data) {
  const tmp = data[0];
  for (const prop in tmp) {
    const camel = pgp.utils.camelize(prop);
    if (!(camel in tmp)) {
      for (let i = 0; i < data.length; i++) {
        const d = data[i];
        d[camel] = d[prop];
        delete d[prop];
      }
    }
  }
}

return massive(massiveConnSettings, {}, driverSettings).then(db => {
  console.log('connected');
  // db.query('create table public.test(column_one int);');
  db.test.insert({ column_one: 1 });
  db.test.find({}).then(resp => {
    console.log('test rows: ', resp);
  });
});
```

## Expected behavior
Expected db.test.insert to insert a new row

## Actual behavior
Massive throws: 

` Error: attempt to overwrite function at public.test is not allowed
    at entities.map.entity (/home/john/code/bugs/massive-camel/node_modules/massive/lib/database.js:107:15)
    at Array.map (<anonymous>)
    at Database.attach (/home/john/code/bugs/massive-camel/node_modules/massive/lib/database.js:84:19)
    at $p.all.then.then.objs (/home/john/code/bugs/massive-camel/node_modules/massive/lib/database.js:273:12)
    at tryCatcher (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/home/john/code/bugs/massive-camel/node_modules/bluebird/js/release/promise.js:638:18)`

**Comment by dmfay** [comment]
Your guess that the camel casing is interfering with introspection seems to be on the money :) The `receive` option [can be set after initialization](https://vitaly-t.github.io/pg-promise/module-pg-promise.html), so you'll want to start looking in the `reload` function in lib/database.js to ensure that the driver (`this.pgp`) doesn't have it set while the reload is actively going on.

**Comment by johnbiundo** [comment]
@dmfay: Thanks for the pointer.  I've tried to figure out how to set an option after initialization, but can't seem to suss it out.  Would you have a further pointer for that?

(It seems I need to access the $config.options member of the underlying db connection, but that is not the same thing as db.pgp.  Constructs like db.pgp.$config don't resolve.  I'm probably off the track on how I'm looking for this, so would welcome any help).

My thought was to see if I could get this to work by setting up receive post initialization and ignore the reload function until after I prove that the startup condition works.

**Comment by dmfay** [comment]
I had the name wrong -- try `this.instance` (the actual instantiation of pg-promise) not `this.pgp`.

**Comment by johnbiundo** [comment]
Awesome, that did it, thanks so much.  

@dmfay: For my use case, this is probably all I need, as my DB is static and doesn't need to be reloaded during the lifetime of the node process.  However, as I offered, I'll be willing to take a look at doing something that might be useful in the more general case if you think it would be worthwhile.

In case anyone else needs this, here's the change from the original problem example above.  It's just a matter of setting the receive option after connecting (to avoid fouling up the introspection process), in the promise resolution, instead of in the driver settings.  The magic bit is using db.instance.$config.options to access the driver settings.

Like so:
```
return massive(massiveConnSettings, {}, driverSettings).then(db => {
  console.log('connected');
  db.instance.$config.options.receive = (data, result, e) => {
    camelizeColumns(data);
  };

  db.test.insert({ column_one: 1 });
  db.test.find({}).then(resp => {
    console.log('test rows: ', resp);
  });
```

**Comment by dmfay** [comment]
I think it'd be useful! What you'd need to do is cache `instance.$config.options.receive` in a variable at the beginning of the `reload` function, delete it, and put it back at the end. For testing, look in test/connect.js; you can copy and paste the "returns a database connection" testcase and add the driver config with `receive` to validate the new behavior. It should be fairly straightforward as these things go, but let me know if it gets confusing.

**Comment by johnbiundo** [comment]
OK, I'll take a look as soon as I can, and won't hesitate to ask for help :)

**Comment by johnbiundo** [comment]
@dmfay Feel free to say no if my experience level appears inadequate for this task.  I'm pretty willing to roll up my sleeves, and go backfill areas I need more background on to proceed, but I probably need a little help getting started, and don't want to be a burden.  

For what it's worth, I'd probably rate myself a good and diligent, but not greatly experienced JS developer.  I do have a ton of RDBMS experience, including primarily PostgreSQL the last couple of years (but going back, believe it or not, to the early Ingres days, when I worked there as a support person), but mostly as a user, not a developer.  And FWIW, I'm greatly interested in becoming a useful contributor to an OS project like this one.

Anyway, I've cloned the repo and wanted to start by running tests, but I'm struggling a little to get them to run properly.  A first attempt yielded many failures :-(  Is there any testing documentation?  I presume I need to set up a DB with permissions and stuff, and could probably reverse engineer that by looking at a bunch of tests, but maybe there's a faster way?

Thanks in advance for any help, and willing to participate, or not, at whatever level makes sense.

**Comment by johnbiundo** [comment]
Oops. Just found https://github.com/dmfay/massive-js/blob/master/CONTRIBUTING.md 

I'll start there :-)

**Comment by johnbiundo** [comment]
@dmfay OK, progress update. 

I've added a few lines to the reload function in database.js:

at the top...

```
Database.prototype.reload = function() {
  this.clean();

  // cache pg-promise receive option config
  const receiveOptionCached = this.instance.$config.options.receive;
  delete this.instance.$config.options.receive;
```

and at the end...

```
        // restore pg-promise receive option config
        this.instance.$config.options.receive = receiveOptionCached
          ? receiveOptionCached
          : null;

        return this;
      });
  });
};
```

One issue and one question:
1) Issue: the transactions > withTransaction > reloads and applies DDL: test fails with:
```
  1) transactions
       withTransaction
         reloads and applies DDL:
     TypeError: Cannot read property 'options' of undefined
      at Database.reload (lib/database.js:66:72)
      at db.withTransaction.co.wrap.mode.db.pgp.txMode.TransactionMode.tiLevel (test/database/with.js:164:23)
      at db.withTransaction.co.wrap.mode.db.pgp.txMode.TransactionMode.tiLevel.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

All other tests pass, including a manual test passing in a receive: camelCase function (exactly like my original code at the top of this report - yay! :) ).  I couldn't really figure out why this one failed.

2) Should I save and restore an empty options.receive as null?  undefined?

Once I get your feedback, I can build a test and send a PR.

Thanks for your assistance!

**Comment by dmfay** [comment]
1. It failed because `this.instance.$config` was undefined when you tried to pull `options.receive` off. I think that's a peculiarity of reloading within a transaction instead of the global context; just make sure `$config` exists before you try to do anything with it.
2. I'd check whether `receiveOptionsCached` is truthy (`if (!!receiveOptionsCached) ...`) before restoring; that way, if there wasn't anything there you don't need to worry about what to put back.

**Comment by dmfay** [comment]
Everything looks good, thank you! I've released v5.7.5.

If there's other stuff you're interested in tackling, feel free to have at it and I'll do my best to field questions :)

**Comment by johnbiundo** [comment]
Awesome.  OK, this was my first OSS contribution.  I'll keep an eye out for more.... I may get addicted :)

Thanks for supporting the effort.

**Comment by dmfay** [comment]
congrats! And beware, it's definitely habit-forming....
