### ISSUE TITLE
Does not work with Oracle??

### ISSUE THREAD

**Issue by nurugger07** [dmfay/massive-js#666]
## Summary
A clear and concise description of the bug or unexpected behavior you're encountering.

### Database setup
```
CREATE TABLE things (
  id SERIAL PRIMARY KEY,
  stuff TEXT
);
```

### Code demonstrating the behavior
```
db.things.find({ stuff: 'this call is breaking' });
```

## Expected behavior
Work with Oracle?

## Actual behavior
Does not work w/ Oracle

## Additional context
Haha Just having fun with #666! Great job @dmfay & thanks for all the hard work :)

**Comment by dmfay** [comment]
:metal: :joy: :metal:

**Comment by xivSolutions** [comment]
@nurugger07 You're doing it wrong. 

If you want to use Massive against Oracle, start with this:

```
DROP DATABASE INCLUDING BACKUPS NOPROMPT;
```

Then just pop open a terminal and do this:

```
sudo apt-get install postgresql
```
